"""Reviewed English strings for the local format converter page."""

ENGLISH_CATALOG: dict[str, str] = {
    "转换引擎": "Conversion engines",
    "输出格式": "Output format",
    "视频编码器": "Video codec",
    "OCR 识别语言": "OCR language",
    "转换结果文本预览": "Converted text preview",
    "预览仅显示前 1 MiB；完整结果需保存后写入输出位置。": (
        "Preview shows only the first 1 MiB. Save the file to write the full result to the output location."
    ),
    "保存全部（%1）": "Save all (%1)",
    "转换已完成，结果暂存在应用临时目录；保存后才会写入所选位置。": (
        "Conversion is complete. The result is staged in the app's temporary folder and will be written to the selected location only after you save it."
    ),
    "清除已完成任务会一并丢弃 %1 个尚未保存的结果。继续吗？": (
        "Clearing finished jobs will also discard %1 unsaved results. Continue?"
    ),
    "移除此任务会丢弃尚未保存的转换结果。继续吗？": (
        "Removing this job will discard its unsaved conversion result. Continue?"
    ),
    "确认丢弃未保存结果": "Confirm discarding unsaved results",
    "丢弃结果": "Discard results",
    "转换完成，结果尚未保存到输出位置；关闭应用前请保存。": (
        "Conversion is complete, but the result has not been saved to the output folder. Save it before closing the app."
    ),
    "正在保存到所选位置…": "Saving to the selected location…",
    "正在保存…": "Saving…",
    "保存此项": "Save this item",
    "添加要转换的文件": "Add files to convert",
    "支持的文件": "Supported files",
    "所有文件 (*)": "All files (*)",
    "选择转换文件的保存位置": "Choose where to save converted files",
    "选择包含图片的文件夹": "Choose a folder containing images",
    "格式转换": "Format converter",
    "本机处理 · 文件不会上传 · 转换结果不会覆盖原文件": (
        "Processed on this device · Files are not uploaded · Original files are never overwritten"
    ),
    "选择文件或直接拖入": "Choose files or drop them here",
    "支持常见图片、文档、表格、电子书和 PDF；安装包内置 FFmpeg 音视频、Tesseract 简体中文/英文 OCR 和 Calibre 电子书引擎，可在转换引擎中分别检查更新。": (
        "Supports common image, document, spreadsheet, e-book, and PDF tasks. "
        "The installer includes FFmpeg for audio/video, Tesseract OCR with Simplified Chinese and English models, and Calibre for e-book conversion. Each engine can be updated separately from Conversion engines."
    ),
    "添加文件": "Add files",
    "文件夹转 PDF": "Folder to PDF",
    "图片文件夹转 PDF": "Images folder to PDF",
    "跟随默认位置": "Follow the default location",
    "已添加 %1 张图片；另有 %2 个文件无法读取。": (
        "Added %1 images; %2 other files could not be read."
    ),
    "已添加 %1 张图片，正在生成 PDF。": "Added %1 images. Creating the PDF.",
    "无法读取所选文件夹。": "Could not read the selected folder.",
    "请选择有效的本机文件夹。": "Choose a valid local folder.",
    "文件夹图片数量超过本机处理上限。": "The folder exceeds this device's image limit.",
    "所选文件夹中没有可读取的图片。": "The selected folder contains no readable images.",
    "选择保存位置": "Choose output folder",
    "保存到：%1": "Save to: %1",
    "默认与源文件保存在同一文件夹": "By default, save beside each source file",
    "转换列表  ·  %1 个文件": "Conversion queue  ·  %1 files",
    "共同目标（%1 个可转换文件）": "Common target (%1 convertible files)",
    "共同目标格式": "Common target format",
    "记住目标格式偏好": "Remember target format preference",
    "开启后，之后添加同类型文件会沿用上次选择。": (
        "When enabled, future files of the same type will use your last choice."
    ),
    "关闭时只影响当前队列，不改变以后文件的默认格式。": (
        "When turned off, this affects only the current queue and leaves the default for future files unchanged."
    ),
    "已为当前 %1 个文件设置目标格式。%2": (
        "Set the target format for the current %1 files. %2"
    ),
    "已记为以后同类文件默认。": "Saved as the default for future files of this type.",
    "未改变以后文件的默认格式。": "The default format for future files was not changed.",
    "应用到所有文件": "Apply to all files",
    "已为 %1 个文件设置目标格式。": "Set the target format for %1 files.",
    "共同目标已变化，请重新选择后再试。": "The common targets changed. Choose a format again and retry.",
    "清除已完成": "Clear completed",
    "开始转换（%1）": "Start conversion (%1)",
    "把文件拖到这里开始": "Drop files here to get started",
    "支持批量添加；可以逐个设置，也可以一次应用所有文件的共同目标格式。": (
        "Add multiple files, choose an output format for each one, or apply a shared target to all files."
    ),
    "选择文件": "Choose files",
    "列表还是空的。添加文件后，可以逐个选择目标格式。": (
        "The queue is empty. Add files, then choose an output format for each one."
    ),
    "转换为": "Convert to",
    "每份 PDF 页数": "Pages per PDF",
    "GIF（保留动画帧）": "GIF (preserve animation frames)",
    "GIF 图像": "GIF image",
    "动图帧数超过本机安全处理上限。": "The animation has too many frames for this device.",
    "动图单帧尺寸超过本机安全处理上限。": "An animation frame exceeds this device's safe pixel limit.",
    "动图累计像素超过本机安全处理上限。": "The animation exceeds this device's total pixel limit.",
    "动图输出超过本机安全体积上限。": "The animated output exceeds this device's size limit.",
    "当前设备没有可用的动图读写组件。": "No animated image component is available on this device.",
    "动图文件无法读取或输出。": "The animated image could not be read or written.",
    "相邻页面连续成组，最后一组可少于设定页数": (
        "Consecutive pages are grouped together; the final group may be smaller."
    ),
    "识别语言": "OCR language",
    "Extract text (OCR)": "Extract text (OCR)",
    "合并为": "Merge as",
    "重试": "Retry",
    "移除": "Remove",
    "已保存：%1": "Saved to: %1",
    "耗时：%1": "Time: %1",
    "预览结果": "Preview result",
    "播放": "Play",
    "暂停": "Pause",
    "格式范围与限制": "Format scope and limitations",
    "不同格式的内容保留程度不同；展开查看对应说明。": (
        "Content preservation varies by format. Expand to see details for each type."
    ),
    "查看格式说明": "View format notes",
    "收起说明": "Hide notes",
    "文本与电子书": "Text and e-books",
    "EPUB 按章节提取文字并简化复杂样式，不保留书中图片；含加密资源或不安全路径的文件会拒绝处理。TXT 支持 UTF-8、GB18030 和带 BOM 的 UTF-16；超出本机上限的文件会被拒绝。PDF→Word 按页面坐标生成可编辑文字；安装包内置 Tesseract 简体中文和英文模型，可识别扫描页。此方式不嵌入 PDF 图片和矢量图，复杂多栏或旋转内容可能需要人工调整。安装包内置 Calibre，可将无 DRM 的 MOBI 转为 EPUB、PDF、DOCX 或 TXT；两个引擎都可单独检查更新。": (
        "EPUB conversions extract text by chapter and simplify complex styles; book images are omitted, and files with encrypted resources or unsafe paths are rejected. TXT supports UTF-8, GB18030, and BOM-marked UTF-16; files above this device's limit are rejected. PDF to Word rebuilds editable text from page coordinates and can OCR scanned pages using the bundled Tesseract Simplified Chinese and English models. PDF images and vector artwork are omitted; complex columns and rotated content may need manual adjustment. The installer includes Calibre for converting DRM-free MOBI files to EPUB, PDF, DOCX, or TXT. Both engines can be updated separately."
    ),
    "PDF": "PDF",
    "可合并队列中的未加密 PDF、按页或每 N 页拆分为 ZIP、导出全部页面图片 ZIP，也可用 AES-256 加密或输入原密码解密。多张图片可排序后合成为多页 PDF，也可把文件夹中的图片按文件名顺序生成 PDF；ZIP 图片包也可转换为 PDF。PDF 还可转换为图片（仅第一页）或提取表格与页面正文；安装包内置 Tesseract 简体中文和英文模型，可识别扫描表格并标注单元格置信度，相邻页同列结构会尝试续接。列对齐不稳定、复杂跨页结构和合并单元格需要人工检查。也可生成带文字层的可搜索 PDF。密码只在本机内存中短暂使用，不写入任务记录，任务结束后清除。": (
        "Queued unencrypted PDFs can be merged, split into ZIPs with one or N pages per PDF, or exported as a ZIP of every page image. Multiple images can be reordered into a multipage PDF; images in a folder can also be turned into a PDF in filename order. ZIP archives of images can be converted to PDF. PDFs can also be converted to an image (first page only), have tables and page text extracted, be protected with AES-256, or be decrypted with the original password. The installer includes Tesseract with Simplified Chinese and English models for scanned-table extraction with per-cell confidence notes; adjacent pages with matching columns are joined when possible. Unstable columns, complex continuations, and merged cells need manual review. Searchable PDF output is also available. Passwords are held briefly in local memory, are not saved to task records, and are cleared when the task ends."
    ),
    "图片": "Images",
    "导出为静态图片时只取首帧；可读取的动图在输出 GIF 或 WebP 时保留动画帧与时长。ICO 输出包含 16、24、32、48、64、128、256 像素图标，不足正方形的图片会透明补边。多张图片可以按顺序合成为多页 PDF。": (
        "Static image outputs use the first frame. Readable animations preserve their frames and timing when exported to GIF or WebP. ICO output contains 16, 24, 32, 48, 64, 128, and 256 pixel frames; nonsquare images are padded transparently. Multiple images can be reordered into a multi-page PDF."
    ),
    "音视频": "Audio and video",
    "安装包已内置 FFmpeg，可离线转换；发布更新后可在“转换引擎”中检查并安装新版本。格式列表按当前编码器支持情况显示。只处理第一条音轨和视频流，不保留字幕、多音轨或复杂章节信息。": (
        "The installer includes FFmpeg for offline conversion. After an update is published, newer versions can be checked and installed in Converter Engines. The format list reflects the available encoders. Only the first audio track and video stream are processed; subtitles, multiple tracks, and complex chapter information are not preserved."
    ),
    "视频编码": "Video codec",
    "H.264 / AVC": "H.264 / AVC",
    "H.265 / HEVC": "H.265 / HEVC",
    "AV1": "AV1",
    "VP9": "VP9",
    "MPEG-4 Part 2": "MPEG-4 Part 2",
    "MS MPEG-4 v3": "MS MPEG-4 v3",
    "Word、Excel 与 PowerPoint": "Word, Excel, and PowerPoint",
    "检测到对应的 Microsoft Office 或 WPS 桌面程序时，PDF 转换会调用本机程序；宏不会运行，Word 和 Excel 不更新外部链接。未安装所需程序时，对应目标格式不会显示。Word 文档的复杂版式、图片、字体、批注和复杂对象不保证保留。": (
        "When the corresponding Microsoft Office or WPS desktop app is detected, PDF conversion uses that local app. Macros do not run, and Word and Excel do not update external links. Targets are hidden when the required app is unavailable. Complex Word layouts, images, fonts, comments, and objects are not reliably preserved."
    ),
    "表格": "Spreadsheets",
    "XLSX 格式转换只读取第一个工作表，不保留样式、图表或公式计算结果；Office 导出 PDF 按工作簿打印设置处理。首行用作列名，重复或空列名会整理；导出 CSV 时可能被识别为公式的文本会加前缀，以降低打开风险。": (
        "XLSX conversions read only the first worksheet and do not preserve styles, charts, or calculated formula results. Office PDF output follows workbook print settings. The first row becomes column names; duplicate or blank names are normalized. Text that spreadsheet software might interpret as a formula is prefixed when exporting CSV."
    ),
    # These fixed labels and errors are supplied by the Python converter bridge,
    # then translated by the QML page through exact-source lookup.
    "暂不支持此格式": "Format not supported",
    "等待转换": "Waiting",
    "正在转换": "Converting",
    "转换完成": "Conversion complete",
    "转换失败": "Conversion failed",
    "此文件类型在当前设备没有可用的本机转换组件。": "No local conversion component for this file type is available on this device.",
    "找不到这个文件，或它不是普通文件。": "The file could not be found or is not a regular file.",
    "文件是空的。": "The file is empty.",
    "文件超过本机转换器的大小上限。": "The file exceeds this device's converter size limit.",
    "当前环境没有安装 XLSX 支持组件 openpyxl。": (
        "The XLSX support component openpyxl is not installed in this environment."
    ),
    "工作簿中没有可读取的工作表。": "The workbook has no readable worksheets.",
    "无法识别文本编码，请先另存为 UTF-8 或 GB18030。": (
        "The text encoding could not be detected. Save the file as UTF-8 or GB18030 and try again."
    ),
    "JSON 顶层需要是对象或数组，才能转换为表格。": (
        "The top-level JSON value must be an object or an array to convert it to a table."
    ),
    "所选格式不适用于这个文件，或当前设备没有对应的转换组件。": (
        "That format is not available for this file, or this device does not have the required conversion component."
    ),
    "图片或 PDF 页面尺寸过大，超过当前转换器的安全处理上限。": (
        "The image or PDF page exceeds this converter's safe processing limit."
    ),
    "图片或 PDF 页面尺寸过大，超过本机安全处理上限。": (
        "The image or PDF page exceeds this device's safe processing limit."
    ),
    "当前环境没有安装 DOCX 支持组件 python-docx。": "The DOCX support component python-docx is not installed in this environment.",
    "当前环境没有安装 PDF 文本支持组件 pypdf。": "The PDF text component pypdf is not installed in this environment.",
    "当前环境没有安装 EPUB 支持组件 lxml。": "The EPUB support component lxml is not installed in this environment.",
    "当前不支持 UTF-32 文本，请先另存为 UTF-8、UTF-16 或 GB18030。": "UTF-32 text is not supported. Save the file as UTF-8, UTF-16, or GB18030 and try again.",
    "UTF-16 文本损坏，请检查原文件编码。": "The UTF-16 text is invalid. Check the source encoding and try again.",
    "源文件超过本机 EPUB 输入上限。": "The source exceeds this device's EPUB input limit.",
    "电子书正文超过本机 EPUB 输出上限。": "The ebook text exceeds this device's EPUB output limit.",
    "电子书章节数量超过本机输出上限。": "The ebook exceeds this device's output chapter limit.",
    "EPUB 文件损坏或结构不受支持，无法读取。": "This EPUB is damaged or uses an unsupported structure.",
    "无法创建 EPUB 文件，请检查磁盘空间和目标文件夹。": "Could not create the EPUB. Check available disk space and the output folder.",
    "按页或每 N 页拆分（ZIP）": "Split every page or every N pages (ZIP)",
    "全部页面图片（ZIP）": "All page images (ZIP)",
    "PDF 表格提取（XLSX）": "Extract PDF tables (XLSX)",
    "当前环境没有安装 PDF 表格提取组件 pdfplumber。": "The PDF table extraction component pdfplumber is not installed in this environment.",
    "PDF 已加密；请先使用原密码解密。": "This PDF is encrypted. Decrypt it with the original password first.",
    "PDF 中没有可提取的页面。": "The PDF has no pages to extract.",
    "PDF 页数超过本机表格提取上限。": "The PDF exceeds this device's table extraction page limit.",
    "PDF 页面数量在读取过程中发生变化，请重新添加文件。": "The PDF page count changed while it was being read. Add the file again.",
    "PDF 提取出的文字超过本机 32 MiB 安全上限。": "The extracted PDF text exceeds this device's 32 MiB safety limit.",
    "PDF 表格单元格总数超过本机处理上限。": "The total number of PDF table cells exceeds this device's processing limit.",
    "PDF 表格数量超过本机处理上限。": "The number of PDF tables exceeds this device's processing limit.",
    "PDF 表格列数超过 Excel 的工作表上限。": "A PDF table exceeds Excel's worksheet column limit.",
    "PDF 中有单元格文字超过 Excel 的长度上限。": "A PDF table cell exceeds Excel's text length limit.",
    "PDF 表格文字总量超过本机 64 MiB 安全上限。": "The extracted PDF table text exceeds this device's 64 MiB safety limit.",
    "未检测到 PDF 内嵌文字或可识别表格；扫描件 OCR 暂不支持。": "No embedded PDF text or recognizable table was detected. OCR for scanned PDFs is not supported yet.",
    "未检测到 PDF 内嵌文字或可识别表格；扫描页需要可用的 Tesseract OCR 引擎。": "No embedded PDF text or recognizable table was detected. Scanned pages require an available Tesseract OCR engine.",
    "扫描页面的 OCR 总像素数超过本机安全上限。": "Scanned pages exceed this device's total OCR pixel limit.",
    "需要 OCR 的扫描页数量超过本机 100 页上限。": "The PDF exceeds this device's limit of 100 scanned pages for OCR.",
    "Qt PDF 引擎无法读取扫描页面。": "The Qt PDF engine could not read the scanned pages.",
    "无法渲染 PDF 页面供 OCR。": "A PDF page could not be rendered for OCR.",
    "无法暂存 PDF 扫描页图片。": "Could not stage a scanned PDF page image.",
    "PDF 表格 OCR 总处理时间超过本机上限。": "PDF table OCR exceeded this device's processing time limit.",
    "OCR 提取出的文字超过本机 32 MiB 安全上限。": "The OCR text exceeds this device's 32 MiB safety limit.",
    "扫描 PDF 表格单元格超过本机 OCR 注释上限。": "The scanned PDF table exceeds this device's OCR annotation limit.",
    "PDF 单页字符数量过大，已停止表格布局分析。": "A PDF page has too many characters for table layout analysis.",
    "PDF 字符总量过大，已停止表格布局分析。": "The PDF has too many characters for table layout analysis.",
    "PDF 单页线条数量过大，已停止表格布局分析。": "A PDF page has too many lines for table layout analysis.",
    "PDF 文字覆盖不足，已拒绝生成可能漏字的 Word 文件。": "PDF text extraction did not cover enough source text, so a possibly incomplete Word file was not created.",
    "当前环境没有安装 PDF 坐标提取组件 pdfplumber。": "The PDF coordinate extraction component pdfplumber is not installed in this environment.",
    "PDF 中没有可转换的页面。": "The PDF has no pages to convert.",
    "PDF 页数超过本机版式重建上限。": "The PDF exceeds this device's page limit for layout reconstruction.",
    "PDF 单页字符数量过大，已停止版式重建。": "A PDF page has too many characters for layout reconstruction.",
    "PDF 字符总量过大，已停止版式重建。": "The PDF has too many characters for layout reconstruction.",
    "PDF 中没有可编辑文字；扫描页面需要可用的 Tesseract OCR 引擎。": "No editable text was found. Scanned pages require an available Tesseract OCR engine.",
    "PDF 含扫描页面；PDF→Word 扫描页重建需要可用的 Tesseract OCR 引擎和对应语言模型。": "This PDF has scanned pages. PDF-to-Word reconstruction requires an available Tesseract engine and matching language model.",
    "PDF→Word OCR 总处理时间超过本机上限。": "PDF-to-Word OCR exceeded this device's processing time limit.",
    "PDF 扫描页面 OCR 未识别出文字。": "OCR did not recognize text on the scanned PDF page.",
    "无法分析 PDF 页面文字与坐标，不能安全重建 Word 版式。": "PDF page text and coordinates could not be analyzed, so its Word layout could not be safely rebuilt.",
    "PDF 中没有可写入 Word 的文字。": "No text was available to write to the Word document.",
    "PDF 页面尺寸超出 Word 文档支持范围。": "The PDF page dimensions exceed the supported Word document range.",
    "DOCX 输出超过本机 128 MiB 安全上限。": "The DOCX output exceeds this device's 128 MiB safety limit.",
    "Tesseract OCR 结果无法解析。": "The Tesseract OCR result could not be parsed.",
    "PDF 表格与正文总量超过本机处理上限。": "The total amount of PDF tables and body text exceeds this device's processing limit.",
    "XLSX 输出超过本机 128 MiB 安全上限。": "The XLSX output exceeds this device's 128 MiB safety limit.",
    "PDF 文件损坏或页面结构不受支持，无法按页拆分。": "This PDF is damaged or uses an unsupported page structure and could not be split.",
    "每个拆分 PDF 的页数必须是整数。": "The page count for each split PDF must be an integer.",
    "每个拆分 PDF 的页数必须在 1 到本机上限之间。": "Pages per split PDF must be between 1 and this device's limit.",
    "拆分结果中的 PDF 页数校验失败。": "A split PDF failed its page-count check.",
    "Qt PDF 引擎无法读取这个文件。": "The Qt PDF engine could not read this file.",
    "PDF 中没有可导出的页面。": "The PDF has no pages to export.",
    "PDF 页数超过本机页面图片导出上限。": "The PDF exceeds this device's page-image export limit.",
    "PDF 页面尺寸无效，无法导出页面图片。": "A PDF page has invalid dimensions and cannot be exported as an image.",
    "PDF 页面尺寸超过本机页面图片像素上限。": "A PDF page exceeds this device's page-image pixel limit.",
    "PDF 页面图片总像素数超过本机处理上限。": "The total pixel count for PDF page images exceeds this device's processing limit.",
    "无法渲染 PDF 页面。": "A PDF page could not be rendered.",
    "无法暂存 PDF 页面图片。": "Could not stage a PDF page image.",
    "无法写入 PDF 页面图片。": "Could not write a PDF page image.",
    "页面图片总量超过本机安全处理上限。": "The page images exceed this device's safe processing limit.",
    "页面图片 ZIP 完整性检查未通过。": "The page-image ZIP failed its integrity check.",
    "页面图片输出校验失败。": "A page-image output failed validation.",
    "PDF 文件损坏或页面结构不受支持，无法导出页面图片。": "This PDF is damaged or uses an unsupported page structure, so its page images could not be exported.",
    "当前不支持 UTF-32 文本，请先另存为 UTF-8、UTF-16 或 GB18030。": "UTF-32 text is not supported. Save the file as UTF-8, UTF-16, or GB18030 and try again.",
    "UTF-16 文本损坏，请检查原文件编码。": "The UTF-16 text is invalid. Check the source encoding and try again.",
    "源文件超过本机 EPUB 输入上限。": "The source exceeds this device's EPUB input limit.",
    "电子书正文超过本机 EPUB 输出上限。": "The ebook text exceeds this device's EPUB output limit.",
    "DOCX 内部文件数量过多，已停止处理。": "This DOCX contains too many internal files, so processing was stopped.",
    "DOCX 解压后的内容超过本机安全处理上限。": "The expanded DOCX content exceeds this device's safe processing limit.",
    "DOCX 内部压缩比例异常，已停止处理。": "This DOCX has an unusual compression ratio, so processing was stopped.",
    "这个文件不是有效的 DOCX 文档。": "This is not a valid DOCX document.",
    "PDF 已加密；当前版本不会尝试密码破解或解锁。": "This PDF is encrypted. This version does not attempt to crack or remove its password.",
    "未检测到可用的 Tesseract OCR 引擎或语言模型。": "No usable Tesseract OCR engine or language model was detected.",
    "所选 OCR 语言不受当前可用引擎支持，请重新选择。": "The selected OCR language is not supported by the available engine. Choose another language.",
    "所选 OCR 语言未随当前组件提供，请重新选择可用语言。": "The selected OCR language is not included in the current engine. Choose an available language.",
    "图片文字识别需要可用的 Tesseract OCR 引擎和语言模型。": "Image OCR requires an available Tesseract engine and language model.",
    "未检测到可用的 Tesseract 与语言模型，扫描页未执行 OCR。": "No usable Tesseract engine and language model were detected. OCR was not run on the scanned pages.",
    "扫描件 OCR 暂不处理加密 PDF，请先用原密码解密。": "OCR does not process encrypted PDFs. Decrypt the PDF with its original password first.",
    "PDF 文件损坏或页面结构不受支持，无法执行 OCR。": "This PDF is damaged or uses an unsupported page structure and cannot be processed with OCR.",
    "PDF 中没有可执行 OCR 的页面。": "The PDF has no pages that can be processed with OCR.",
    "PDF 页数超过本机 OCR 安全上限。": "The PDF exceeds this device's OCR page limit.",
    "Qt PDF 引擎无法读取这个文件。": "The Qt PDF engine could not read this file.",
    "PDF 页面尺寸无效，已停止 OCR。": "A PDF page has invalid dimensions, so OCR was stopped.",
    "PDF 页面总像素数超过本机 OCR 安全上限。": "The PDF exceeds this device's OCR pixel limit.",
    "无法渲染 PDF 页面。": "A PDF page could not be rendered.",
    "无法生成 OCR 临时页面。": "A temporary OCR page could not be created.",
    "OCR 处理超时，请缩小文件或分批处理。": "OCR timed out. Reduce the file size or process it in smaller batches.",
    "OCR 总处理时间超过本机上限。": "OCR exceeded this device's total processing time limit.",
    "无法启动可用的 Tesseract OCR 引擎。": "The available Tesseract OCR engine could not be started.",
    "Tesseract OCR 失败，请检查可用的语言模型。": "Tesseract OCR failed. Check that its language model is available.",
    "OCR 输出超过本机 PDF 大小上限。": "The OCR output exceeds this device's PDF size limit.",
    "OCR PDF 输出为空或超过本机大小上限。": "The OCR PDF output is empty or exceeds this device's size limit.",
    "OCR PDF 输出校验失败。": "The OCR PDF output did not pass validation.",
    "PDF 已加密，当前版本不会尝试密码破解或解锁。": "This PDF is encrypted. This version does not attempt to crack or remove its password.",
    "PDF 中没有可拆分的页面。": "This PDF has no pages to split.",
    "PDF 页数超过本机拆分上限。": "The PDF exceeds this device's page limit for splitting.",
    "拆分后文件总量超过本机安全处理上限。": "The split output exceeds this device's safe processing limit.",
    "拆分后的 ZIP 完整性检查未通过。": "The split ZIP failed its integrity check.",
    "拆分结果中的单页 PDF 校验失败。": "A single-page PDF in the split output failed validation.",
    "EPUB 内部路径无效，已停止处理。": "This EPUB contains an invalid internal path, so processing was stopped.",
    "EPUB 内部路径超出压缩包范围，已停止处理。": "This EPUB contains a path outside its archive, so processing was stopped.",
    "EPUB 包内不允许引用外部资源。": "This EPUB references external resources, which are not allowed.",
    "这个 EPUB 不符合电子书容器结构要求。": "This EPUB does not have the required container structure.",
    "EPUB 内部文件数量过多，已停止处理。": "This EPUB contains too many internal files, so processing was stopped.",
    "EPUB 含有不安全的内部路径，已停止处理。": "This EPUB contains an unsafe internal path, so processing was stopped.",
    "EPUB 内部文件名重复或大小写冲突，已停止处理。": "This EPUB has duplicate or case-conflicting internal file names, so processing was stopped.",
    "EPUB 含有符号链接，已停止处理。": "This EPUB contains a symbolic link, so processing was stopped.",
    "EPUB 解压后的内容超过本机安全处理上限。": "The expanded EPUB exceeds this device's safe processing limit.",
    "EPUB 内部压缩比例异常，已停止处理。": "This EPUB has an unusual compression ratio, so processing was stopped.",
    "EPUB 内部文件已加密，当前版本无法读取。": "This EPUB contains encrypted archive entries, which this version cannot read.",
    "这个文件不是有效的 EPUB 电子书。": "This is not a valid EPUB book.",
    "EPUB 含有加密资源，当前版本无法读取。": "This EPUB contains encrypted resources, which this version cannot read.",
    "EPUB 缺少容器目录信息。": "The EPUB is missing its container directory information.",
    "EPUB 没有指定有效的书籍目录文件。": "The EPUB does not specify a valid package document.",
    "EPUB 书籍目录文件不存在。": "The EPUB package document is missing.",
    "EPUB 缺少章节顺序信息。": "The EPUB is missing its chapter order information.",
    "EPUB 章节目录引用了缺失的内容文件。": "The EPUB spine references a missing content file.",
    "EPUB 章节内容文件不存在。": "An EPUB chapter content file is missing.",
    "EPUB 章节数量超过本机处理上限。": "The EPUB exceeds this device's chapter limit.",
    "EPUB 提取出的文字超过本机处理上限。": "The extracted EPUB text exceeds this device's processing limit.",
    "EPUB 中没有可读取的章节文字。": "No readable chapter text was found in this EPUB.",
    "源文件没有可写入 EPUB 的正文内容。": "The source file has no content to write to EPUB.",
    "生成的 EPUB 完整性检查未通过。": "The generated EPUB failed its integrity check.",
    "生成的 EPUB 容器结构校验失败。": "The generated EPUB container structure is invalid.",
    "无法按页拆分 PDF：%1": "Could not split PDF into pages: %1",
    "无法读取 EPUB 电子书：%1": "Could not read EPUB book: %1",
    "无法创建 EPUB 电子书：%1": "Could not create EPUB book: %1",
    "PDF 页数超过本机文本提取上限。": "The PDF exceeds this device's page limit for text extraction.",
    "PDF 提取出的文字过多，超过本机处理上限。": "The extracted PDF text exceeds this device's processing limit.",
    "PDF 中没有可提取的文字。扫描件需要 OCR，本阶段尚未接入。": (
        "No extractable text was found in this PDF. Scanned documents need OCR, which is not included yet."
    ),
    "不适用于文档转换的输入格式。": "This input format is not supported for document conversion.",
    "无法创建 PDF 输出。": "Could not create the PDF output.",
    "找不到 Windows PowerShell，无法启动本机 Office 转换。": "Windows PowerShell was not found, so local Office conversion cannot start.",
    "本机 Office 转换超时，已停止等待。": "The local Office conversion timed out and was stopped.",
    "本机 Office 转换失败，请确认 Office 已激活且文件未加密，然后重试。": (
        "Local Office conversion failed. Make sure Office is activated, the file is not encrypted, and try again."
    ),
    "本机 Office 没有生成有效的转换文件。": "Local Office did not create a valid output file.",
    "尚不支持所选文档输出格式。": "That document output format is not supported yet.",
    "尚不支持所选表格输出格式。": "That table output format is not supported yet.",
    "PNG": "PNG",
    "JPEG": "JPEG",
    "BMP": "BMP",
    "CUR": "CUR",
    "GIF first frame": "GIF 首帧",
    "ICNS": "ICNS",
    "ICO": "ICO",
    "ICO（多尺寸）": "ICO (multi-size)",
    "按静态画面处理；GIF 只读取首帧，ICO 输出包含 16、24、32、48、64、128、256 像素图标，不足正方形的图片会透明补边。多张图片可以按顺序合成为多页 PDF。": (
        "Images are processed as static frames; GIF uses only its first frame. ICO output includes 16, 24, 32, 48, 64, 128 and 256 pixel images, with transparent padding when needed. Multiple images can also be combined into a multipage PDF."
    ),
    "SVG": "SVG",
    "WebP": "WebP",
    "TIFF": "TIFF",
    "CSV": "CSV",
    "TSV": "TSV",
    "JSON": "JSON",
    "Excel workbook (XLSX)": "Excel 工作簿（XLSX）",
    "Plain text (TXT)": "纯文本（TXT）",
    "Markdown (MD)": "Markdown（MD）",
    "HTML document": "HTML 网页",
    "Word document (DOCX)": "Word 文档（DOCX）",
    "PDF document": "PDF 文档",
    "EPUB book": "EPUB 电子书",
    "ZIP 图片包转 PDF": "ZIP image archive to PDF",
    "PDF from ordered images": "按顺序合成的 PDF",
    "图片合并为 PDF": "Combine images into PDF",
    "调整图片顺序后生成多页 PDF；每张图片各占一页，原文件不会被修改。": (
        "Reorder images to create a multipage PDF, with one image per page. Source images are unchanged."
    ),
    "已略过 %1 张不可读取、正在转换或已移除的图片。": (
        "Skipped %1 images that cannot be read, are converting, or were removed."
    ),
    "至少需要两张可读取的图片；当前可合并 %1 张。": (
        "At least two readable images are required; %1 can currently be merged."
    ),
    "合并 %1 张图片": "Combine %1 images",
    "PDF pages (ZIP)": "PDF 分页压缩包（ZIP）",
    "Searchable PDF (OCR)": "Searchable PDF (OCR)",
    "Merged PDF": "合并后的 PDF",
    "合并 PDF": "Merge PDFs",
    "调整文件顺序后再合并。合并会生成新文件，原 PDF 不会被修改。": (
        "Review the file order before merging. A new file will be created, and the source PDFs will not be changed."
    ),
    "已略过 %1 个无法合并的 PDF（例如加密、损坏或正在转换）。": (
        "Skipped %1 PDFs that cannot be merged, such as encrypted, damaged, or currently converting files."
    ),
    "位置：%1": "Location: %1",
    "↑ 上移": "↑ Move up",
    "↓ 下移": "↓ Move down",
    "至少需要两份可读取且未加密的 PDF；当前可合并 %1 份。": (
        "At least two readable, unencrypted PDFs are required; %1 can currently be merged."
    ),
    "无法开始合并，请重新检查队列。": "Could not start the merge. Check the queue and try again.",
    "合并 %1 个 PDF": "Merge %1 PDFs",
    "合并需要选择 2 至 500 张图片。": "Choose between 2 and 500 images to combine.",
    "合并列表中不能重复选择同一张图片。": "The same image cannot be selected more than once.",
    "队列状态已变化，请重新检查图片合并顺序。": (
        "The queue changed. Review the image order and try again."
    ),
    "合并至少需要两份有效 PDF。": "Select at least two valid PDFs to merge.",
    "合并列表中不能重复选择同一文件。": "The same file cannot be selected more than once.",
    "队列状态已变化，请重新检查合并顺序。": (
        "The queue changed. Review the merge order and try again."
    ),
    "MP3 audio": "MP3 音频",
    "WAV audio": "WAV 音频",
    "FLAC audio": "FLAC 音频",
    "M4A audio": "M4A 音频",
    "AAC audio": "AAC 音频",
    "OGG audio": "OGG 音频",
    "Opus audio": "Opus 音频",
    "WMA audio": "WMA 音频",
    "MP4 video": "MP4 视频",
    "MKV video": "MKV 视频",
    "MOV video": "MOV 视频",
    "WebM video": "WebM 视频",
    "AVI video": "AVI 视频",
    "所选视频编码在这个输出格式中不可用。": "The selected video codec is not available for this output format.",
    "所选视频编码器不可用。": "The selected video encoder is unavailable.",
    "未找到本机 Calibre ebook-convert 程序。": "Calibre ebook-convert is not available on this device.",
    "无法启动本机 Calibre ebook-convert 程序。": "Could not start Calibre ebook-convert on this device.",
    "MOBI 转换超时，已停止处理。": "MOBI conversion timed out and was stopped.",
    "本机 Calibre 无法读取 MOBI 文件；文件可能损坏或受 DRM 保护。": "Local Calibre could not read the MOBI file. It may be damaged or DRM-protected.",
    "本机电子书转换未生成有效文件。": "The local e-book converter did not create a valid file.",
    "电子书输出超过本机 256 MiB 上限。": "The e-book output exceeds this device's 256 MiB limit.",
    "电子书输出完整性检查未通过。": "The e-book output failed its integrity check.",
    "%1% complete": "已完成 %1%",
    "PDF password protection (AES-256)": "PDF 密码加密（AES-256）",
    "Remove PDF password": "PDF 解密（需原密码）",
    "PDF 加密密码": "PDF encryption password",
    "原 PDF 密码": "Original PDF password",
    "设置密码（至少 8 个字符）": "Set a password (at least 8 characters)",
    "输入原 PDF 密码": "Enter the original PDF password",
    "至少 8 个字符": "At least 8 characters",
    "输入原密码": "Enter the original password",
    "%1 (first page only)": "%1（仅第一页）",
    "%1 · %2": "%1 · %2",
    "Microsoft Word": "Microsoft Word",
    "Microsoft Excel": "Microsoft Excel",
    "Microsoft PowerPoint": "Microsoft PowerPoint",
    "请输入 PDF 密码。": "Enter a PDF password.",
    "PDF 密码长度超过本机输入上限。": "The PDF password exceeds this device's input limit.",
    "PDF 加密密码至少需要 8 个字符。": "PDF encryption passwords must be at least 8 characters.",
    "这个 PDF 已加密，请先使用原密码解密。": "This PDF is already encrypted. Decrypt it with the original password first.",
    "这个 PDF 没有加密，无需解密。": "This PDF is not encrypted, so it does not need to be decrypted.",
    "PDF 密码不正确，无法解密。": "The PDF password is incorrect, so it could not be decrypted.",
    "PDF 中没有可处理的页面。": "This PDF has no pages to process.",
    "PDF 页数超过本机安全处理上限。": "The PDF exceeds this device's safe page limit.",
    "PDF 输出超过本机安全处理上限。": "The PDF output exceeds this device's safe processing limit.",
    "加密后的 PDF 完整性检查未通过。": "The encrypted PDF failed its integrity check.",
    "解密后的 PDF 完整性检查未通过。": "The decrypted PDF failed its integrity check.",
    "PDF 页面完整性检查未通过。": "The PDF page integrity check failed.",
    "PDF 文件损坏或安全处理失败，未能完成加密/解密。": "The PDF is damaged or its security operation failed, so encryption/decryption could not be completed.",
    "至少选择两个未加密 PDF 才能合并。": "Choose at least two unencrypted PDFs to merge.",
    "合并列表中存在重复 PDF 文件。": "The merge list contains duplicate PDF files.",
    "合并列表中有无效 PDF 文件。": "The merge list contains an invalid PDF file.",
    "加密或无法读取的 PDF 不能直接合并。": "Encrypted or unreadable PDFs cannot be merged directly.",
    "合并列表中含有加密 PDF，请先使用原密码解密。": "The merge list contains an encrypted PDF. Decrypt it with the original password first.",
    "合并后的 PDF 页数超过本机处理上限。": "The merged PDF exceeds this device's page limit.",
    "合并列表中的 PDF 没有可用页面。": "The merge list contains no usable PDF pages.",
    "合并后的 PDF 超过本机 512 MiB 输出上限。": "The merged PDF exceeds this device's 512 MiB output limit.",
    "合并后的 PDF 页面完整性检查未通过。": "The merged PDF failed its page integrity check.",
    "PDF 文件损坏或页面结构不受支持，无法合并。": "A PDF is damaged or uses an unsupported structure, so the files could not be merged.",
    "合并 PDF 失败，未保留部分输出。": "PDF merging failed; no partial output was kept.",
    "本机没有可用的 FFmpeg 程序。": "FFmpeg is not available on this device.",
    "所选音视频输出格式或编码器不可用。": "The selected audio/video format or encoder is unavailable.",
    "音视频源文件超过本机 2 GiB 处理上限。": "The audio/video source exceeds this device's 2 GiB limit.",
    "音视频时长超过本机 4 小时处理上限。": "The audio/video duration exceeds this device's 4-hour limit.",
    "所选音视频转换方向不受支持。": "The selected audio/video conversion is not supported.",
    "无法启动本机 FFmpeg 程序。": "Could not start local FFmpeg.",
    "音视频转换超时，已停止处理。": "The audio/video conversion timed out and was stopped.",
    "本机 FFmpeg 无法用当前编码器转换此文件。": "Local FFmpeg could not convert this file with the available codecs.",
    "FFmpeg 没有生成有效的音视频文件。": "FFmpeg did not create a valid audio/video output.",
    "音视频输出超过本机 4 GiB 处理上限。": "The audio/video output exceeds this device's 4 GiB limit.",
    "所选音频编码器不可用。": "The selected audio encoder is unavailable.",
    "WebM 所需的本机编码器不可用。": "The local codecs required for WebM are unavailable.",
    "本机没有可用的视频编码器。": "No video encoder is available on this device.",
    "无法读取转换结果预览。": "Could not read the conversion preview.",
    "预览仅显示前 1 MiB；完整文件保存在输出位置。": "Preview is limited to the first 1 MiB; the full file remains in the output folder.",
    "没有可合并的图片。": "No images are available to combine.",
    "图片格式不支持：%1": "Unsupported image format: %1",
    "图片尺寸过大，超过本机安全处理上限。": "An image exceeds this device's safe processing limits.",
    "合并图片的总像素数超过本机安全处理上限。": "The combined images exceed this device's total pixel limit.",
    "PDF 写入失败，没有生成有效文件。": "PDF writing failed and no valid file was created.",
    "生成的 PDF 超过本机 512 MiB 输出上限。": "The generated PDF exceeds this device's 512 MiB output limit.",
    "ZIP 内部文件数量过多，已停止处理。": "The ZIP archive contains too many entries.",
    "ZIP 解压后的内容超过本机安全处理上限。": "The expanded ZIP content exceeds this device's safety limit.",
    "ZIP 中没有可读取的图片文件。": "The ZIP archive contains no readable images.",
    "ZIP 中图片超过 500 张上限。": "The ZIP archive exceeds the 500-image limit.",
    "ZIP 中包含加密图片，无法处理。": "The ZIP archive contains encrypted images and cannot be processed.",
    "ZIP 内图片为空或超过本机单文件大小上限。": "A ZIP image is empty or exceeds this device's per-file limit.",
    "ZIP 图片压缩比过高，已停止处理。": "A ZIP image has an excessive compression ratio.",
    "ZIP 图片总展开大小超过本机安全处理上限。": "The expanded ZIP images exceed this device's safety limit.",
    "ZIP 图片实际展开大小超过声明值或安全上限。": "An expanded ZIP image exceeds its declared size or safety limit.",
    "ZIP 图片长度与目录记录不符，压缩包可能损坏。": "A ZIP image length does not match the archive directory; the archive may be damaged.",
    "ZIP 文件损坏或内部图片无法安全读取。": "The ZIP archive is damaged or its images cannot be read safely.",
    "将保存 %1 项到：%2": "Save %1 items to: %2",
    "将保存 %1 项到各自的计划位置": "Save %1 items to their planned locations.",
    "设置默认保存位置": "Set the default save location",
    "选择本次任务保存位置": "Choose a save location for this batch",
    "本次任务保存到…": "Save this batch to…",
    "默认位置（下次仍使用）：%1": "Default location (used next time): %1",
    "默认位置：与源文件保存在同一文件夹": "Default location: beside each source file",
    "本次任务位置：%1；开始转换后会固定到每个结果。": "Batch location: %1. Each result will use this location after conversion starts.",
    "本次任务位置：跟随默认位置；开始转换后会固定到每个结果。": "Batch location: follow the default. Each result will use this location after conversion starts.",
    "正在保存": "Saving",
    "待保存": "Ready to save",
    "将保存到：%1": "Will save to: %1",
    "正在保存到：%1": "Saving to: %1",
    "已生成，待保存到：%1": "Ready to save to: %1",
    "保存到此位置": "Save to this location",
    "当前任务暂不支持": "This task is not supported.",
    "不是可合并的 PDF 任务": "This task is not a mergeable PDF.",
    "当前任务需要先解密": "This task must be decrypted first.",
    "源文件已不存在": "The source file no longer exists.",
    "文件内容不是可读取的 PDF": "The file does not contain a readable PDF.",
    "PDF 受密码保护": "The PDF is password-protected.",
    "无法读取 PDF": "The PDF could not be read.",
    "不是可合并的图片任务": "This task is not a mergeable image.",
    "图片尺寸超过本机限制": "The image dimensions exceed this device's limit.",
    "图片无法读取": "The image could not be read.",
    "当前文件未纳入合并": "This file is not included in the merge.",
    "等待当前任务完成后再合并": "Wait for the current task to finish before merging.",
    "检查转换组件或重新添加文件": "Check the conversion component or add the file again.",
    "检查转换组件": "Check the conversion component.",
    "重新添加原始 PDF": "Add the original PDF again.",
    "先完成解密，再把解密后的 PDF 加入合并": "Decrypt the PDF first, then add the decrypted file to the merge.",
    "重新添加这个文件": "Add this file again.",
    "重新导出或重新添加有效 PDF": "Export the PDF again or add a valid PDF.",
    "先输入密码解密，再合并解密后的 PDF": "Enter the password to decrypt the PDF, then merge the decrypted file.",
    "检查文件是否损坏，再重新添加": "Check whether the file is damaged, then add it again.",
    "重新添加原始图片": "Add the original image again.",
    "缩小图片后再添加": "Resize the image, then add it again.",
    "重新检查后再试": "Review the files and try again.",
    "将按下方清单合并 %1 个 PDF；原 PDF 不会被修改。调整顺序后再提交。": "The %1 PDFs below will be merged. The originals will not be changed. Review the order before continuing.",
    "将按下方清单生成 %1 页 PDF；原图片不会被修改。调整顺序后再提交。": "A %1-page PDF will be created from the images below. The originals will not be changed. Review the order before continuing.",
    "另有 %1 个 PDF 未纳入合并。": "%1 other PDFs are excluded from the merge.",
    "另有 %1 张图片未纳入合并。": "%1 other images are excluded from the merge.",
    "收起原因": "Hide reasons",
    "查看原因": "View reasons",
}
