"""Reviewed English text for the daily-flow page."""

ENGLISH_CATALOG: dict[str, str] = {
    "专注任务": "Focus task",
    "一项日程": "one calendar item",
    "日期未记录": "Date not recorded",
    "把昨天收好，再开始今天。": "Close out yesterday, then start today.",
    "记录回顾、安排待办，为眼前一件事留出完整时间。": "Review your notes, plan tasks, and make uninterrupted time for one thing at hand.",
    "昨日回顾": "Yesterday review",
    "仅汇总此工作台记录": "Only entries from this workspace",
    "昨天留下的记录": "Yesterday's entries",
    "%1 条": "%1 items",
    "昨天留给今天的线索": "A note to carry into today",
    "昨天没有留下“明早跟进”的内容。": "No follow-up note was left for this morning.",
    "给明天的自己留一句跟进线索": "Leave a follow-up note for tomorrow",
    "例如：继续跟进昨天没完成的事项……": "For example: continue the item I didn't finish yesterday...",
    "保存跟进线索": "Save follow-up note",
    "问题簿": "Question book",
    "最多保留 12 条；新增会替换最早一条": "Keep up to 12; adding one replaces the oldest",
    "记下今天想弄明白的一件事": "Write down one thing you want to understand today",
    "收进问题簿 +": "Add to question book +",
    "问题簿还是空的。先记下一件想弄明白的事。": "Your question book is empty. Add something you want to understand.",
    "移除": "Remove",
    "待办摘要 · 邮件与日历尚未连接": "Task summary · Email and calendar are not connected",
    "今天的待办": "Today's tasks",
    "%1 项": "%1 items",
    "已完成": "Completed",
    "工作收件箱": "Work inbox",
    "尚未集成": "Not connected",
    "这里只提供网页邮箱快捷入口；应用不会读取邮件内容或日历事项。": "These are shortcuts to webmail only. The app does not read email or calendar data.",
    "打开 Gmail 网页 ↗": "Open Gmail on the web ↗",
    "打开 Outlook 网页 ↗": "Open Outlook on the web ↗",
    "选择一件事，为它留出一段完整时间": "Choose one task and make uninterrupted time for it",
    "25 分钟 · 本机计时": "25 minutes · local timer",
    "番茄钟": "Pomodoro",
    "Flowtime 正向计时": "Flowtime",
    "自定义倒计时": "Custom countdown",
    "计时方式": "Timer mode",
    "倒计时分钟": "Countdown minutes",
    "%1 分钟": "%1 minutes",
    "番茄钟 · 25 分钟 · 本机保存": "Pomodoro · 25 minutes · saved locally",
    "Flowtime · 正向计时 · 本机保存": "Flowtime · counts up · saved locally",
    "自定义倒计时 · %1 分钟 · 本机保存": "Custom countdown · %1 minutes · saved locally",
    "结束并保存": "Finish and save",
    "计时进行中，进度与工作时段会保存到本机。": "The timer is running. Progress and work sessions are saved locally.",
    "已用时间已保存在本机；恢复后可继续或切换任务。": "Elapsed time is saved locally. Resume or switch tasks when you return.",
    "计时方式、检查点与任务关联保存在本机。": "Timer mode, checkpoint, and task link are saved locally.",
    "这一段先做什么？": "What will you work on now?",
    "手动输入本轮任务或下一步": "Enter a task for this focus session or the next step",
    "选择一项今日待办…": "Choose one of today's tasks…",
    "选择今日待办后，专注计时会同步记录实际用时；手写任务只运行专注钟。": "When you choose a task for today, the focus timer also records time spent. A custom task only runs the timer.",
    "今天没有可关联的待办；手写任务会单独运行专注钟。": (
        "No tasks are available to link today. A manually entered task will run the focus timer on its own."
    ),
    "重置": "Reset",
    "计时进行中": "Timer is running",
    "计时器状态保存在当前运行会话中。": "Timer state is kept for the current session.",
    "本轮专注已锁定当前任务；暂停后可以切换任务。": (
        "This focus session is locked to the current task. Pause it to switch tasks."
    ),
    "Spotify 外部播放": "Spotify playback",
    "链接保存在本机。应用不嵌入网页播放器；点击外部打开后由系统默认浏览器或 Spotify 应用接手播放。": "The link is saved on this device. The app does not embed a web player; playback opens in your default browser or Spotify app.",
    "Spotify 单曲、专辑、播放列表或播客链接": "Spotify track, album, playlist, or podcast link",
    "在 Spotify 打开 ↗": "Open in Spotify ↗",
    "保存链接": "Save link",
    "移除保存的链接": "Remove saved link",
    "今日工作": "Today's work",
    "开始专注": "Start focus session",

    # Values below are fixed labels returned by the daily and planner models.
    # The QML translates their presentation while keeping the stored values intact.
    "记录": "Entry",
    "财务": "Finance",
    "健康": "Health",
    "日程": "Planner",
    "待买": "To buy",
    "习惯": "Habit",
    "影音": "Media",
    "生活": "Life",
    "工作": "Work",
    "家庭": "Family",
    "个人": "Personal",
    "全天": "All day",
    "继续专注": "Resume focus",
    "暂停": "Pause",
    "再来一轮": "Start another round",

    # Exact empty-state messages and user-visible results/errors from the bridges.
    "昨天在这套工作台里还没有个人记录。": "There are no personal entries in this workspace for yesterday.",
    "今天还没有待办，给自己留点空间": "There are no tasks for today yet. Leave yourself some room.",
    "明日跟进线索已保存。": "Follow-up note saved for tomorrow.",
    "Spotify 链接已保存。": "Spotify link saved.",
    "问题已加入问题簿。": "Question added to the question book.",
    "问题已从问题簿移除。": "Question removed from the question book.",
    "移除问题": "Remove question",
    "确定从问题簿移除“%1”？移除后不会出现在今天工作台。": (
        "Remove “%1” from the question book? It will no longer appear on today's workbench."
    ),
    "已保存，明天复盘时回看。": "Saved to review tomorrow.",
    "计时已重置。": "Focus timer reset.",
    "专注任务已保存。": "Focus task saved.",
    "已移除保存的链接。": "Saved link removed.",
    "问题已收进问题簿。": "Question added to the question book.",
    "已移除这条问题。": "Question removed.",
    "已开始记录日程实际用时。": "Task time tracking started.",
    "日程实际用时已记录。": "Task time has been recorded.",
    "日程实际用时已保存。": "Task time has been saved.",
    "日程实际用时已继续记录。": "Task time tracking resumed.",
    "专注计时已暂停并保存。": "Focus timer paused and saved.",
    "专注计时已开始。": "Focus timer started.",
    "计时方式已保存。": "Timer mode saved.",
    "已恢复记录日程实际用时。": "Task time tracking restored.",
    "上一项日程实际用时已记录。": "Previous task time has been recorded.",
    "已将链接交给系统默认浏览器或 Spotify 应用。": "The link was handed off to your default browser or Spotify app.",
    "系统未能打开 Spotify 链接，请检查默认浏览器或 Spotify 应用。": "Could not open the Spotify link. Check your default browser or Spotify app.",
    "请先保存有效的 Spotify 单曲、专辑、播放列表或播客链接。": "Save a valid Spotify track, album, playlist, or podcast link first.",
    "操作未保存，请检查本机存储状态后重试。": "The change was not saved. Check local storage and try again.",
    "操作失败，请稍后重试。": "The operation failed. Try again later.",
    "每日流程暂不可用。": "Daily flow is temporarily unavailable.",
    "每日流程数据暂时无法载入。": "Daily flow data could not be loaded right now.",
    "生活记录暂时无法同步到昨日回顾。": "Life records could not be synced to yesterday's review right now.",
    "昨日回顾暂时无法更新习惯记录。": "Yesterday's review could not update habit records right now.",
    "保存失败，请检查本机数据后重试。": "Save failed. Check local data and try again.",
    "请提供旧版支持的 Spotify 单曲、专辑、播放列表或播客链接。": "Provide a Spotify track, album, playlist, or podcast link supported by the previous version.",
    "问题不能为空。": "Question cannot be empty.",
    "问题时间无效。": "Question timestamp is invalid.",
    "问题位置无效。": "Question index is invalid.",
    "这条问题已不存在。": "This question no longer exists.",
    "专注时长必须是正整数秒。": "Focus duration must be a positive whole number of seconds.",
    "专注计时模式无效。": "Focus timer mode is invalid.",
    "已用专注时间无效。": "Elapsed focus time is invalid.",
    "倒计时须为 5 至 480 分钟。": "Countdown must be between 5 and 480 minutes.",
    "请先暂停计时，再调整计时方式。": "Pause the timer before changing its mode.",
    "剩余专注时间无效。": "Remaining focus time is invalid.",
    "计时状态无效。": "Timer state is invalid.",
    "计时步进必须是非负整数秒。": "Timer step must be a non-negative whole number of seconds.",
    "日程功能暂不可用。": "Planner is temporarily unavailable.",
    "这项待办已不存在，列表已刷新。": "This task no longer exists. The list has been refreshed.",
    "计时任务无效。": "Timed task is invalid.",
    "已完成的事项不能开始计时。": "Completed tasks cannot be timed.",
    "请先结束当前任务的计时，再开始另一项。": "Stop timing the current task before starting another.",
    "明日跟进线索最多 500 个字符。": "Follow-up notes for tomorrow can contain up to 500 characters.",
    "专注任务最多 100 个字符。": "A focus task can contain up to 100 characters.",
    "Spotify 链接最多 300 个字符。": "A Spotify link can contain up to 300 characters.",
    "问题最多 160 个字符。": "A question can contain up to 160 characters.",
    "日期必须使用 YYYY-MM-DD 日期。": "Date must use the YYYY-MM-DD format.",
    "日期必须使用有效日期。": "Date must be valid.",
    "日程数据暂时无法载入。": "Planner data could not be loaded right now.",
    "日程操作没有保存，请检查后重试。": "The planner change was not saved. Check the data and try again.",
    "当前计时的检查点时间无效。": "The current timer checkpoint is invalid.",
    "新版保留有效 Spotify 链接，并交由系统默认浏览器或 Spotify 应用打开。桌面核心不嵌入网页播放器；Windows 外部打开行为仍待实际验证。": "The new version keeps valid Spotify links and opens them in the default browser or Spotify app. The desktop app does not embed a web player; external opening on Windows still needs verification.",
}
