"""English translations for the finance Qt Quick page."""

ENGLISH_CATALOG: dict[str, str] = {
    "全部分类": "All categories",
    "本月支出超出预算 %1": "This month's spending is over budget by %1",
    "今天尚无账目；本月统计仅包含已记录的数据。": (
        "No transactions recorded today; monthly totals include recorded entries only."
    ),
    "已新增 20 笔账目，建议导出完整备份。": (
        "You've added 20 transactions. Consider exporting a full backup."
    ),
    "已保存。": "Saved.",
    "操作未完成，请检查后重试。": "The operation didn't complete. Check the details and try again.",
    "金额必须是大于 0 的有效数字。": "Enter a valid amount greater than 0.",
    "请选择有效分类。": "Choose a valid category.",
    "这笔账已保存到本机。": "Transaction saved on this device.",
    "流水已删除。": "Transaction deleted.",
    "导出记账流水": "Export transactions",
    "Excel 工作簿 (*.xlsx)": "Excel workbooks (*.xlsx)",
    "Excel 流水已导出到所选位置。": (
        "The Excel transaction report was exported to the selected location."
    ),
    "删除这条流水？": "Delete this transaction?",
    "删除后，这条流水只会从当前本机账本中隐藏；导入的旧版原始数据不会被改动。": (
        "After deletion, this transaction is hidden from the current local ledger; imported legacy source data stays unchanged."
    ),
    "取消": "Cancel",
    "删除": "Delete",
    "选择日期": "Choose a date",
    "上个月": "Previous month",
    "%1年 %2月": "Month %2, %1",
    "下个月": "Next month",
    "日": "Sun",
    "一": "Mon",
    "二": "Tue",
    "三": "Wed",
    "四": "Thu",
    "五": "Fri",
    "六": "Sat",
    "今天": "Today",
    "关闭": "Close",
    "收支手账": "Income & expense tracker",
    "导出 Excel": "Export to Excel",
    "本机保存 · 导入的旧版数据不会被改动": "Saved locally · Imported legacy data will not be changed",
    "本月收入": "Income this month",
    "本月支出": "Spending this month",
    "本月结余": "Balance this month",
    "日均支出": "Average daily spending",
    "月度预算": "Monthly budget",
    "本月预算金额": "Budget amount for this month",
    "预算 %1": "Budget: %1",
    " · 默认值": " · Default",
    "当前使用应用默认预算 %1；设置后按你的实际月预算统计。": (
        "The app's default budget is %1. Set your own monthly budget to use it for tracking."
    ),
    "已使用 %1%": "%1% used",
    "剩余 %1": "%1 remaining",
    "设置本月预算": "Set this month's budget",
    "例如 5000": "For example, 5000",
    "更新预算": "Update budget",
    "设置预算": "Set budget",
    "月度预算已更新。": "Monthly budget updated.",
    "本月最多：%1 %2": "Top category this month: %1 · %2",
    "本月尚无支出分类": "No spending categories this month",
    " · 单笔最高：%1": " · Largest single expense: %1",
    "上月支出 %1 · 暂无可比基数": "Last month's spending: %1 · No comparison baseline yet",
    "上月支出 %1 · 本月%2 %3（%4%）": "Last month: %1 · This month %2 %3 (%4%)",
    "增加": "increased by",
    "减少": "decreased by",
    "持平": "unchanged at",
    "记一笔账": "Add a transaction",
    "支出": "Expense",
    "收入": "Income",
    "类型": "Type",
    "收支类型": "Income or expense type",
    "金额": "Amount",
    "必填：金额": "Required: amount",
    "必填，例如 12.50": "Required, for example 12.50",
    "分类": "Category",
    "收支分类": "Income or expense category",
    "日期": "Date",
    "打开日期选择": "Open date picker",
    "使用今天": "Use today",
    "选日期": "Choose date",
    "备注": "Note",
    "备注（最多 60 字）": "Note (up to 60 characters)",
    "可选，最多 60 字": "Optional, up to 60 characters",
    "记下这笔": "Save transaction",
    "消费结构": "Spending breakdown",
    "%1 · 分类支出": "%1 · Spending by category",
    "本月还没有支出记录。": "No spending recorded this month.",
    "流水": "Transactions",
    "流水筛选已更新。": "Transaction filter updated.",
    "还没有符合筛选条件的账目。": "No transactions match this filter.",
    "未分类": "Uncategorized",
}
