"""Reviewed English text for the fitness page."""

ENGLISH_CATALOG: dict[str, str] = {
    "记录体重后即可查看趋势": "Record your weight to see the trend",
    "再记录一次体重，就能看到趋势": "Record your weight once more to see the trend",
    "已保存。": "Saved.",
    "操作未完成，请检查后重试。": "The action was not completed. Check and try again.",
    "体重需填写 20–300 kg 的有效数字。": "Enter a valid weight from 20 to 300 kg.",
    "运动分钟需为 0–1440 的整数。": "Exercise minutes must be a whole number from 0 to 1440.",
    "身体记录已保存到本机。": "Body record saved on this device.",
    "记录已删除。": "Record deleted.",
    "周计划已删除。": "Weekly plan deleted.",
    "目标档案已保存。": "Goal profile saved.",
    "计划已加入本周安排。": "Plan added to this week.",
    "身体": "Body",
    "这项计划": "This plan",
    "导出健身记录": "Export fitness records",
    "Excel 工作簿 (*.xlsx)": "Excel workbook (*.xlsx)",
    "健身记录已导出。": "Fitness records exported.",
    "删除这条身体记录？": "Delete this body record?",
    "删除后，这条身体记录不会再出现在当前本机记录中；导入的旧版原始数据不会被改动。": "After deletion, this body record will no longer appear in the current local records; imported legacy source data stays unchanged.",
    "删除": "Delete",
    "删除这项计划？": "Delete this plan?",
    "目标设置": "Goal settings",
    "起始体重用于计算目标进度；身高和目标体重用于 BMI 与目标估算。": "Starting weight is used for goal progress; height and target weight are used for BMI and estimates.",
    "身高（cm）": "Height (cm)",
    "例如：165": "e.g. 165",
    "起始体重（kg）": "Starting weight (kg)",
    "例如：60.0": "e.g. 60.0",
    "目标体重（kg）": "Target weight (kg)",
    "例如：55.0": "e.g. 55.0",
    "保存目标": "Save goals",
    "添加周计划": "Add weekly plan",
    "周计划只用于健身安排，不会创建日程提醒。": "Weekly plans are for fitness planning and do not create calendar reminders.",
    "类别": "Category",
    "计划名称": "Plan name",
    "例如：快走 3 次": "For example: brisk walks ×3",
    "必填：例如：快走 3 次": "Required: for example, brisk walks ×3",
    "补充说明": "Additional details",
    "频次、时长或具体做法": "Frequency, duration, or details",
    "加入计划": "Add plan",
    "健康与运动": "Health & fitness",
    "导出 Excel": "Export Excel",
    "当前体重": "Current weight",
    "未记录": "Not recorded",
    "目标未设置": "Goal not set",
    "BMI 待计算": "BMI unavailable",
    "距离目标": "Remaining to goal",
    "当前 BMI": "Current BMI",
    "目标进度": "Goal progress",
    "目标已达成": "Goal reached",
    "稳稳向 %1 kg 前进": "Moving steadily toward %1 kg",
    "先设置个人体重目标": "Set your personal weight goal first",
    "请填写身高、起始体重和目标体重后查看进度。": "Enter your height, starting weight, and target weight to see goal progress.",
    "请先记录体重，再设置身高和体重目标。": "Record your weight, then set your height and weight goal.",
    "起点 %1 kg": "Starting point %1 kg",
    "目标 %1 kg": "Target %1 kg",
    "已达到当前目标。": "You have reached your current goal.",
    "记录两次以上后，可参考体重变化估算进度。": "After at least two records, weight changes can be used to estimate progress.",
    "按近期趋势估算，约还需 %1 天。": "Based on the recent trend, about %1 days remain.",
    "每日记录": "Daily record",
    "保存后的记录会显示在这里。": "Saved records will appear here.",
    "体重记录必填，运动时长可留空。": "Weight is required; exercise duration is optional.",
    "体重（kg）": "Weight (kg)",
    "例如 64.5": "For example: 64.5",
    "必填：例如 64.5": "Required: for example, 64.5",
    "运动分钟（选填）": "Exercise minutes (optional)",
    "日期": "Date",
    "备注（最多 60 字）": "Note (up to 60 characters)",
    "可以留空": "Optional",
    "保存身体记录": "Save body record",
    "体重趋势": "Weight trend",
    "记录体重后查看变化": "Record your weight to see changes",
    "已有 1 次有效体重记录": "1 valid weight record so far",
    "趋势时间范围": "Trend time range",
    "近 30 天": "Last 30 days",
    "近 90 天": "Last 90 days",
    "近 1 年": "Last year",
    "全部": "All time",
    "当前范围内 %1 次测量 · 圆点为记录，虚线为最多 7 次均值": "%1 measurements in this range · dots are records; dashed line averages up to 7",
    "这个时间范围内没有体重记录，试试选择更长的范围。": "No weight records in this range. Try a longer range.",
    "体重": "Weight",
    "最多 7 次均值": "Up to 7-record average",
    "趋势估算待积累": "More records needed for an estimate",
    "预计约 %1 天": "About %1 days estimated",
    "本周计划": "This week's plan",
    "%1 / %2 已完成 · 还有 %3 项": "%1 / %2 complete · %3 remaining",
    "新增计划": "Add plan",
    "标记计划未完成": "Mark plan as incomplete",
    "标记计划已完成": "Mark plan as complete",
    "计划完成状态已更新。": "Plan completion status updated.",
    "未命名计划": "Untitled plan",
    "按自己的节奏完成": "Go at your own pace",
    "还没有周计划，添加一项适合自己的安排。": "No weekly plans yet. Add one that works for you.",
    "最近身体记录": "Recent body records",
    "显示最近 20 条 · 导出包含全部记录": "Showing the latest 20 · export includes all records",
    "身体记录": "Body record",
    " · %1 分钟运动": " · %1 min exercise",
    "还没有身体记录。": "No body records yet.",
}
