"""Reviewed English strings for the habits Qt Quick page."""

ENGLISH_CATALOG: dict[str, str] = {
    "每天": "Every day",
    "指定星期": "Selected weekdays",
    "频率": "Frequency",
    "每周 %1": "Weekly: %1",
    "请至少选择一个计划日。": "Select at least one scheduled day.",
    "星期%1": "Weekday %1",
    "非计划日": "Not scheduled",
    "今天没有计划打卡的习惯": "No habits are scheduled for today",
    "今天没有计划打卡的习惯，休息日不会影响连续记录。": (
        "No habits are scheduled today. Rest days do not break your streak."
    ),
    "今天没有计划打卡的习惯，休息也算计划内。": (
        "No habits are scheduled today. Rest days are part of the plan."
    ),
    "%1 · %2 · 非计划日": "%1 · %2 · Not scheduled",
    "%1 次": "%1 times",
    "按计划日连续达成": "Consecutive scheduled completions",
    "休息": "Rest day",
    "尚未开始": "Not started yet",
    "%1 · %2 · 尚未开始": "%1 · %2 · Not started yet",
    "30 天习惯热力图": "30-Day Habit Heatmap",
    "30 天完成率": "30-Day Completion Rate",
    "开始记录后显示": "Shown once you start tracking",
    "最近 30 天还没有记录": "No records in the last 30 days",
    "先添加一项习惯": "Add a habit first",
    "✓ 今日完成": "✓ Done today",
    "一": "Mon",
    "三": "Wed",
    "习惯": "Habit",
    "习惯列表为空。新增一项后，可以用勾选、计数或数值方式记录。": (
        "Your habit list is empty. Add one to track it with a check, a count, or a number."
    ),
    "习惯已删除。": "Habit deleted.",
    "二": "Tue",
    "五": "Fri",
    "今天打卡": "Today's check-in",
    "今日习惯": "Today's habits",
    "今日完成": "Completed today",
    "今日记录已更新。": "Today's record was updated.",
    "例如：分钟、页": "For example: minutes, pages",
    "例如：阅读、散步": "For example: reading, walking",
    "六": "Sat",
    "减少计数": "Decrease count",
    "删除": "Delete",
    "删除「%1」及其本机打卡记录？此操作无法撤销。": (
        "Delete “%1” and its local check-in history? This cannot be undone."
    ),
    "删除习惯": "Delete habit",
    "勾选": "Check",
    "单位": "Unit",
    "单位最多 6 个字符。": "The unit must be 6 characters or fewer.",
    "历史最长打卡": "Longest streak",
    "取消": "Cancel",
    "名称": "Name",
    "更多习惯操作": "More habit actions",
    "周%1": "Week %1",
    "四": "Thu",
    "增加计数": "Increase count",
    "完成": "Done",
    "完成一点，就算前进。记录留在本机，可随时回看。": (
        "Every small step counts. Your records stay on this device and are always here to revisit."
    ),
    "完成目标的习惯": "Habits that meet their goal",
    "已保存。": "Saved.",
    "已记录": "Recorded",
    "建立一项适合自己的日常记录。": "Create a daily habit that suits you.",
    "建立一项适合自己的记录计划。": "Create a tracking plan that suits you.",
    "撤销": "Undo",
    "操作未完成，请重试。": "The operation did not complete. Try again.",
    "数值": "Number",
    "新习惯已添加。": "New habit added.",
    "新增习惯": "Add a habit",
    "编辑习惯": "Edit habit",
    "保存修改": "Save changes",
    "习惯设置已更新。": "Habit settings updated.",
    "计划从今天起生效，之前的记录仍按旧计划统计。": "The new schedule starts today; earlier entries keep their original schedule.",
    "日": "Sun",
    "昨天完成 %1 / %2 项习惯。": "Yesterday: %1 of %2 habits completed.",
    "昨天完成 %1 项习惯。": "Yesterday: %1 habits completed.",
    "昨天的记录会汇总在这里，帮你看到持续的小进步。": (
        "Yesterday's records will appear here, so you can see the small steps adding up."
    ),
    "昨日回顾": "Yesterday's review",
    "暖沙色": "Warm sand",
    "最佳连续": "Best streak",
    "最近 7 天": "Last 7 days",
    "未命名习惯": "Unnamed habit",
    "本机习惯数据": "Local habit data",
    "柔和紫": "Soft lavender",
    "样本习惯已清理。": "Sample habits were cleared.",
    "样本习惯记录已清空。": "Sample habit check-ins were cleared.",
    "每日完成概览": "Daily completion overview",
    "灰白为无记录，浅色为部分记录，深色为达成目标": (
        "Gray cells have no entry; light cells are partial; dark cells meet the goal."
    ),
    "已完成": "Completed",
    "未完成": "Not completed",
    "%1 / %2 %3": "%1 / %2 %3",
    "%1 %2": "%1 %2",
    "%1 · %2 · %3": "%1 · %2 · %3",
    "添加习惯": "Add habit",
    "添加习惯后，这里会显示每天的记录。": "Daily records will appear here once you add a habit.",
    "清理样本": "Clear samples",
    "清理样本习惯": "Clear sample habits",
    "清理样本习惯…": "Clear sample habits…",
    "清空样本记录": "Clear sample check-ins",
    "清空样本记录…": "Clear sample check-ins…",
    "清空样本习惯记录": "Clear sample habit check-ins",
    "清空样本习惯的历史记录，并将这些习惯保留为普通习惯；你自己添加的习惯不会受影响。": (
        "Clear the sample habits' history and keep them as regular habits. Habits you added will not be affected."
    ),
    "清空这些样本习惯的打卡记录，并将习惯保留为普通习惯；你自己添加的习惯不会受影响。": (
        "Clear check-ins for sample habits and keep the habits as regular habits. Habits you added will not be affected."
    ),
    "点一下，更新今天的记录": "Tap to update today's record",
    "生活记录  /  习惯健康": "Life records  /  Habits & health",
    "目标": "Goal",
    "目标请填写 0.1 到 999 之间的数字。": "Enter a goal between 0.1 and 999.",
    "确认删除": "Confirm deletion",
    "色调": "Color",
    "计数": "Count",
    "记录方式": "Tracking method",
    "请先填写习惯名称。": "Enter a habit name first.",
    "近一个月的坚持": "Consistency over the last month",
    "还没有习惯，先添加一项吧": "No habits yet. Add one to get started.",
    "这个习惯": "this habit",
    "陶土色": "Terracotta",
    "鼠尾草绿": "Sage green",
    "＋ 新增习惯": "＋ Add a habit",
    "：": ": ",
}
