"""English translations for the books and media Qt Quick page."""

ENGLISH_CATALOG: dict[str, str] = {
    "作品名称": "Title",
    "记录日期": "Entry date",
    "一句话短评": "Short review",
    "作品类型": "Media type",
    "观看状态": "Viewing status",
    "作品评分": "Rating",
    "按观看状态筛选": "Filter by viewing status",
    "按评分筛选": "Filter by rating",
    "日": "Sun",
    "一": "Mon",
    "二": "Tue",
    "三": "Wed",
    "四": "Thu",
    "五": "Fri",
    "六": "Sat",
    "草稿自动保存": "Draft auto-saved",
    "未评分": "Unrated",
    "已保存。": "Saved.",
    "操作未完成，请检查后重试。": "The operation didn't complete. Check the details and try again.",
    "作品名称不能为空。": "Enter a title.",
    "作品已加入书影音清单。": "Added to your media list.",
    "作品已加入；但表单草稿清理失败：%1": "Added to your media list, but the form draft could not be cleared: %1",
    "草稿未保存。": "The draft was not saved.",
    "草稿保存失败": "Could not save draft",
    "草稿已保存": "Draft saved",
    "作品已从本机清单移除。": "Removed from your local media list.",
    "封面已压缩为本机 JPEG。": "The cover was compressed to a local JPEG.",
    "封面处理失败，请重新选择。": "Could not process the cover. Choose another image.",
    "已切换状态筛选。": "Status filter updated.",
    "已切换评分筛选。": "Rating filter updated.",
    "选择本机封面图片": "Choose a cover image on this device",
    "图片或其他文件 (*)": "Images or other files (*)",
    "从书影音清单删除？": "Remove this item from your media list?",
    "移除后，这部作品不会再出现在当前本机书影音清单；导入的旧版原始数据不会被改动。": (
        "After removal, this title will no longer appear in the current local media list; imported legacy source data stays unchanged."
    ),
    "取消": "Cancel",
    "删除": "Delete",
    "选择记录日期": "Choose a date",
    "上个月": "Previous month",
    "下个月": "Next month",
    "%1 年 %2 月": "%2/%1",
    "今天": "Today",
    "书影音收藏": "Books and media",
    "本机保存 · 封面只在本机处理 · 导入的旧版数据不会被改动": (
        "Saved locally · Covers are processed on this device · Imported legacy data will not be changed"
    ),
    "记下一部作品": "Add a title",
    "保存在本机": "Saved on this device",
    "电影、剧、书或番的名字": "Movie, series, book, or anime title",
    "必填：电影、剧、书或番的名字": "Required: movie, series, book, or anime title",
    "暂不评分": "Not rated",
    "记录日期 YYYY-MM-DD": "Date (YYYY-MM-DD)",
    "选择日期": "Choose date",
    "一句话短评（最多 100 字）": "Short review (up to 100 characters)",
    "封面已就绪": "Cover ready",
    "选择本机封面": "Choose a local cover",
    "≤12MB · 处理为 360×480 以内 JPEG": "≤12 MB · Processed as JPEG, up to 360 × 480 px",
    "可选 · 不会上传": "Optional · Never uploaded",
    "清除": "Clear",
    "移除封面": "Remove cover",
    "加入我的书影音": "Add to my media list",
    "%1 年看完": "%1 completed",
    "今年看完": "Completed this year",
    "%1 部": "%1 titles",
    "平均评分": "Average rating",
    "最爱类型": "Favorite type",
    "今年看完作品的评分分布": "Ratings for titles completed this year",
    "%1 星": "%1 stars",
    "下一段精神旅程": "Your next reading or viewing",
    "%1 在看 · %2 想看": "%1 in progress · %2 on your list",
    "待读与在看条目均为 0。": "There are no items to read or watch right now.",
    "封面墙": "Cover wall",
    "已切换到封面墙。": "Switched to the cover wall.",
    "列表": "List",
    "已切换到列表。": "Switched to the list.",
    "全部状态": "All statuses",
    "全部评分": "All ratings",
    "5 星": "5 stars",
    "4 星以上": "4+ stars",
    "3 星以上": "3+ stars",
    "这个筛选条件下还没有作品。": "No titles match this filter.",
    "无封面": "No cover",
    "未命名": "Untitled",
    "这部作品": "This title",
    "作品": "Title",
    "日期未知": "Date unknown",
    "电影": "Movie",
    "剧": "Series",
    "书": "Book",
    "番": "Anime",
    "想看": "Want to watch",
    "在看": "Watching",
    "看完": "Finished",
    "弃了": "Dropped",
    "书影音功能暂不可用。": "The media feature is not available right now.",
    "图片处理组件不可用，请检查桌面运行环境。": (
        "Image processing is unavailable. Check the desktop runtime."
    ),
    "封面必须来自本机图片文件。": "Choose a cover image from this device.",
    "封面文件无法读取。": "The cover file could not be read.",
    "封面文件为空。": "The cover file is empty.",
    "封面图片请控制在 12MB 以内。": "Cover images must be 12 MB or smaller.",
    "封面格式不支持或图片已损坏。": "The cover format is unsupported or the image is damaged.",
    "封面暂时无法转换。": "The cover could not be converted right now.",
    "封面暂时无法转换为 JPEG。": "The cover could not be converted to JPEG right now.",
    "封面图片处理失败。": "Could not process the cover image.",
    "作品名称最多 60 个字符。": "Titles can contain up to 60 characters.",
    "请选择电影、剧、书或番。": "Choose a movie, series, book, or anime.",
    "请选择有效的作品状态。": "Choose a valid title status.",
    "评分必须是 0 到 5 的整数。": "Rating must be a whole number from 0 to 5.",
    "短评必须是文本。": "The review must be text.",
    "短评最多 100 个字符。": "Reviews can contain up to 100 characters.",
    "封面数据无效。": "The cover data is invalid.",
    "新增封面必须是本机处理后的 JPEG 图片。": (
        "New covers must be JPEG images processed on this device."
    ),
    "封面数据无效，请重新选择图片。": "The cover data is invalid. Choose the image again.",
    "处理后的封面图片过大。": "The processed cover image is too large.",
    "媒体记录 id 必须是非空文本。": "A media record ID must be non-empty text.",
    "媒体记录 id 已存在。": "That media record ID already exists.",
    "媒体记录 id 已被本机删除标记占用。": (
        "That media record ID is already used by a local deletion marker."
    ),
    "媒体记录 id 无效。": "The media record ID is invalid.",
    "视图必须是 wall 或 list。": "The view must be wall or list.",
    "请选择有效的作品状态筛选。": "Choose a valid status filter.",
    "评分筛选必须为 0、3、4 或 5。": "The rating filter must be 0, 3, 4, or 5.",
    "书影音表单草稿必须是对象。": "The media form draft must be an object.",
}

DISAMBIGUATED_ENGLISH_CATALOG: dict[tuple[str, str], str] = {}
