"""Reviewed English strings for planning, scheduling, and time tracking."""

ENGLISH_CATALOG: dict[str, str] = {
    "仍有待处理提醒": "Pending reminders",
    "无法确认提醒状态": "Reminder status unavailable",
    "当前系统无法提供托盘提醒。为避免错过提醒，请保持窗口打开，或仍然退出软件。": (
        "This system cannot provide tray reminders. To avoid missing reminders, "
        "keep the window open or exit anyway."
    ),
    "日程数据暂时无法检查。为避免漏掉提醒，请先保持窗口打开并检查数据。": (
        "Planner data cannot be checked right now. Keep the window open and check the data "
        "to avoid missing reminders."
    ),
    "保持打开": "Keep window open",
    "仍然退出": "Exit anyway",
    "日程提醒": "Planner reminder",
    "该处理这件日程了。": "Time to take care of this task.",
    "任务清单": "Task list",
    "任务优先级": "Task priority",
    "任务日期": "Task date",
    "任务时间": "Task time",
    "日期": "Date",
    "时间": "Time",
    "预估时长": "Estimated duration",
    "重复周期": "Repeat schedule",
    "按项目筛选": "Filter by project",
    "按标签筛选": "Filter by tag",
    "计时方式": "Timer mode",
    "看板列状态": "Board column status",
    "看板列标签": "Board column tag",
    "待办备注": "Task notes",
    "%1 小时 %2 分": "%1 hr %2 min",
    "%1 小时": "%1 hr",
    "%1 分钟": "%1 min",
    "%1 分": "%1 min",
    "已安排到 %1。": "Scheduled for %1.",
    "未标日期": "Undated",
    "周日": "Sun",
    "周一": "Mon",
    "周二": "Tue",
    "周三": "Wed",
    "周四": "Thu",
    "周五": "Fri",
    "周六": "Sat",
    " · 今天": " · Today",
    "%1 月 %2 日 · %3%4": "%1/%2 · %3%4",
    "这件待办": "this task",
    "日程统筹": "Planner",
    "草稿自动保存": "Draft autosave",
    "安排今天的节奏，也留意接下来一周": "Plan your day and keep an eye on the week ahead",
    "本机保存": "Saved on this device",
    "今天": "Today",
    "今天 %1 项 · 逾期 %2 项 · 未来七天 %3 项": (
        "Today %1 · %2 overdue · %3 in the next seven days"
    ),
    "刷新": "Refresh",
    "待办": "To do",
    "进行中": "In progress",
    "完成": "Done",
    "已逾期": "Overdue",
    "未来 7 天": "Next 7 days",
    "添加待办": "Add a task",
    "编辑待办": "Edit task",
    "保存修改": "Save changes",
    "取消编辑": "Cancel editing",
    "编辑": "Edit",
    "日程已更新。": "Task updated.",
    "样例待办不能编辑。": "Sample tasks cannot be edited.",
    "来源已取消的待办不能编辑。": "Tasks canceled at their source cannot be edited.",
    "编辑这项待办？": "Edit this task?",
    "当前有未提交的待办草稿。继续编辑会清除这份草稿。": (
        "There is an unfinished task draft. Continuing will discard the draft."
    ),
    "继续保留草稿": "Keep the draft",
    "放弃草稿并编辑": "Discard draft and edit",
    "草稿会自动保存在本机": "Drafts are saved automatically on this device",
    "要做什么？": "What needs to be done?",
    "选择日期": "Choose date",
    "时间可留空，待办会出现在下方“待安排”，之后可拖到日内时间轴。": (
        "You can leave the time blank. The task will appear under Unscheduled and can be dragged "
        "onto the daily timeline later."
    ),
    "时间可留空，未安排的待办可稍后拖入日内时间轴。": (
        "The time can be left blank. Unscheduled tasks can be dragged onto the daily timeline later."
    ),
    "普通": "Normal",
    "高优先级": "High priority",
    "低优先级": "Low priority",
    "估计 15 分钟": "Estimate 15 min",
    "估计 30 分钟": "Estimate 30 min",
    "估计 45 分钟": "Estimate 45 min",
    "估计 1 小时": "Estimate 1 hr",
    "估计 1.5 小时": "Estimate 1.5 hr",
    "估计 2 小时": "Estimate 2 hr",
    "估计 3 小时": "Estimate 3 hr",
    "不重复": "No repeat",
    "每天": "Daily",
    "每个工作日": "Weekdays",
    "每周": "Weekly",
    "每月": "Monthly",
    "备注：地点、准备事项或补充说明": "Notes: location, preparations, or other details",
    "所属项目（可选）": "Project (optional)",
    "标签，以逗号分隔": "Tags, separated by commas",
    "工作台打开时提醒我": "Remind me while the workspace is open",
    "加入日程": "Add to planner",
    "子任务 %1/%2": "Subtasks %1/%2",
    "这项任务": "this task",
    "子任务 +": "Subtask +",
    "为此任务添加子任务": "Add a subtask to this task",
    "添加子任务": "Add subtask",
    "添加到：%1": "Add to: %1",
    "子任务要做什么？": "What needs to be done in this subtask?",
    "子任务内容": "Subtask details",
    "例如：检查安装包": "For example: check the installer",
    "加入": "Add",
    "确定删除“%1”及其 %2 个子任务吗？删除后无法撤回。": (
        "Delete “%1” and its %2 subtasks? This action cannot be undone."
    ),
    "任务状态暂不可修改。": "Task status cannot be changed right now.",
    "状态已更新为 %1。": "Status updated to %1.",
    "更多": "More",
    "预估": "Estimate",
    "重复": "Repeat",
    "备注": "Note",
    "提醒": "Reminder",
    "收起更多选项": "Hide additional options",
    "展开更多选项": "Show more options",
    "更多（已设置 %1 项）": "More (%1 configured)",
    "展开更多选项，已设置：%1": "Show more options, configured: %1",
    "更多已设置：%1": "More configured: %1",
    "保存": "Save",
    "更多选项：项目、标签、预估、重复、备注与提醒": (
        "More options: project, tags, time estimate, repeat, notes, and reminder"
    ),
    "视图暂不可切换。": "The view cannot be changed right now.",
    "视图已切换。": "View changed.",
    "筛选暂不可用。": "Filters are unavailable right now.",
    "项目和标签筛选已更新。": "Project and tag filters updated.",
    "全部项目": "All projects",
    "全部标签": "All tags",
    "项目": "Project",
    "标签": "Tag",
    "所属项目": "Project",
    "可选": "Optional",
    "任务标签": "Task tags",
    "用逗号分隔": "Separate with commas",
    "地点、准备事项或补充说明": "Location, preparation, or additional notes",
    "订阅名称": "Subscription name",
    "订阅地址": "Subscription URL",
    "账户名称": "Account name",
    "CalDAV 日历集地址": "CalDAV calendar collection URL",
    "账号": "Username",
    "密码 / 应用专用密码": "Password / app-specific password",
    "项目/标签": "Project/tags",
    "编辑项目和标签": "Edit project and tags",
    "项目和标签已保存。": "Project and tags saved.",
    "专注": "Focus",
    "任务计时 · 已记录 %1": "Task timer · %1 logged",
    "Flowtime · 已专注 %1": "Flowtime · focused %1",
    "番茄钟": "Pomodoro",
    "倒计时": "Countdown",
    " · 已暂停 · 剩余 %1": " · Paused · %1 left",
    " · 已暂停": " · Paused",
    " · 剩余 %1": " · %1 left",
    "结束并保存": "Finish and save",
    "继续": "Resume",
    "暂停": "Pause",
    "继续专注": "Resume focus",
    "暂停专注": "Pause focus",
    "已继续专注。": "Focus resumed.",
    "专注已暂停。": "Focus paused.",
    "专注计时暂不可用。": "Focus timer is unavailable right now.",
    "番茄钟已开始。": "Pomodoro started.",
    "Flowtime 专注已开始。": "Flowtime started.",
    "倒计时已开始。": "Countdown started.",
    "计时已继续。": "Timer resumed.",
    "计时已暂停。": "Timer paused.",
    "计时结果已保存。": "Tracked time saved.",
    "工时复盘": "Timesheet review",
    "从": "From",
    "到": "To",
    "更新统计": "Refresh report",
    "导出 CSV": "Export CSV",
    "导出工时 CSV": "Export timesheet CSV",
    "CSV 文件 (*.csv)": "CSV files (*.csv)",
    "工时 CSV 已导出。": "Timesheet CSV exported.",
    "每日工时": "Daily time",
    "实际 %1 · 估算 %2 · 差额 %3": "Actual %1 · Estimated %2 · Difference %3",
    "专注 %1 次 · 活跃 %2 天 · 日均 %3 · 估算准确度 %4%": "Focus %1 sessions · Active %2 days · Daily avg %3 · Estimate accuracy %4%",
    "专注 %1 次": "Focus sessions: %1",
    "实际 %1": "Actual %1",
    "估算 %1": "Estimated %1",
    "任务估算与实际": "Task estimates and actuals",
    "项目汇总": "Project totals",
    "标签汇总": "Tag totals",
    "关闭": "Close",
    "工时复盘暂不可用。": "Timesheet review is unavailable right now.",
    "导入日历": "Import calendar",
    "日历来源": "Calendar sources",
    "打开日历来源菜单": "Open calendar sources menu",
    "导出 ICS": "Export ICS",
    "日历订阅": "Calendar subscriptions",
    "添加只读 iCalendar 订阅。建议使用 HTTPS；链接会在本机加密保存，不会显示在列表中。": (
        "Add a read-only iCalendar subscription. HTTPS is recommended; the link is encrypted on this device and hidden from the list."
    ),
    "名称（可留空）": "Name (optional)",
    "HTTPS / webcal 日历订阅地址": "HTTPS / webcal calendar subscription URL",
    "添加并同步": "Add and sync",
    "订阅已保存，正在首次同步。": "Subscription saved. First sync is underway.",
    "订阅已保存；请查看同步状态。": "Subscription saved. Check its sync status.",
    "日历订阅暂不可用。": "Calendar subscriptions are unavailable right now.",
    "已开始刷新日历订阅。": "Calendar subscription refresh started.",
    "全部刷新": "Refresh all",
    "已开始刷新全部日历订阅。": "All calendar subscription refreshes started.",
    "订阅和它同步的日程已删除；手动导入的日程不受影响。": (
        "The subscription and its synced events were removed. Manually imported events were kept."
    ),
    "刷新失败时会保留上次成功同步的事件。删除订阅会删除其缓存事件。": (
        "A failed refresh keeps the last successful events. Removing a subscription deletes its cached events."
    ),
    "正在同步…": "Syncing…",
    "最近成功：%1": "Last successful sync: %1",
    "尚未成功同步": "No successful sync yet",
    "缓存事件：%1": "Cached events: %1",
    "还没有添加日历订阅。": "No calendar subscriptions yet.",
    "添加订阅后，可在此查看最近同步状态和缓存事件数。": (
        "After adding a subscription, its latest sync status and cached event count will appear here."
    ),
    "删除日历订阅": "Remove calendar subscription",
    "删除“%1”及其同步的缓存日程？手动导入的日程不会删除。": (
        "Remove “%1” and its synced cached events? Manually imported events will be kept."
    ),
    "删除订阅和缓存": "Remove subscription and cache",
    "CalDAV 账户": "CalDAV accounts",
    "填写具体的 CalDAV 日历集地址。已保存账户会在应用启动时及此后每小时自动同步，也可手动立即同步支持的 VEVENT 日程和 VTODO 待办；VEVENT 只读，重复待办暂不支持。只有服务器提供强 ETag 时才会回写 VTODO 完成状态。账号密码在本机加密保存，含登录信息的地址必须使用 HTTPS。": (
        "Saved accounts sync automatically when the app starts and every hour afterward. You can also manually sync supported VEVENT events and VTODO tasks. VEVENT events are read-only, and recurring VTODO tasks are not supported yet. Writing back VTODO completion requires a strong ETag from the server. Credentials are encrypted on this device, and URLs with login credentials must use HTTPS."
    ),
    "账户名称（可留空）": "Account name (optional)",
    "公开日历可留空": "Leave blank for public calendars",
    "HTTPS CalDAV 日历集地址": "HTTPS CalDAV calendar collection URL",
    "账号（公开日历可留空）": "Username (leave blank for public calendars)",
    "密码或应用专用密码": "Password or app password",
    "保存并检测": "Save and check",
    "重新检测": "Check again",
    "正在检查…": "Checking…",
    "尚未成功检查": "Not checked successfully yet",
    "连接成功，可读取：%1": "Connected; available components: %1",
    "日历事件": "calendar events",
    "待办任务": "tasks",
    "日历集": "calendar collection",
    "移除": "Remove",
    "还没有添加 CalDAV 账户。": "No CalDAV accounts yet.",
    "添加账户后，可在此查看连接状态并同步支持的 VEVENT 日程和 VTODO 待办。": (
        "After adding an account, you can check its connection status and sync supported VEVENT events and VTODO tasks here. Saved accounts also sync automatically when the app starts and every hour."
    ),
    "CalDAV 账户暂不可用。": "CalDAV accounts are unavailable right now.",
    "账户已保存，正在检查日历集。": "Account saved; checking the calendar collection.",
    "正在检查 CalDAV 日历集。": "Checking the CalDAV calendar collection.",
    "同步待办": "Sync tasks",
    "正在同步 CalDAV 待办。": "Syncing CalDAV tasks.",
    "正在同步待办…": "Syncing tasks…",
    "同步日历内容": "Sync calendar content",
    "正在同步 CalDAV 日历内容。": "Syncing CalDAV calendar content.",
    "正在同步日历内容…": "Syncing calendar content…",
    "最近同步：%1": "Last synced: %1",
    "CalDAV 账户和本机保存的登录信息已移除。": "CalDAV account and locally saved credentials removed.",
    "移除 CalDAV 账户": "Remove CalDAV account",
    "移除“%1”会删除本机保存的登录信息和它同步的日历事件；已导入的远程待办会保留为本机记录，但不再同步。继续吗？": (
        "Removing “%1” deletes its locally saved credentials and synced calendar events. "
        "Imported remote tasks remain as local records but will no longer sync. Continue?"
    ),
    "移除账户和同步内容": "Remove account and synced content",
    "CalDAV 账户和本机同步内容已移除。": "CalDAV account and local synced content removed.",
    "日历导入暂不可用。": "Calendar import is unavailable right now.",
    "日历已导入：新增 %1，更新 %2，未变 %3。": "Calendar imported: %1 added, %2 updated, %3 unchanged.",
    "另导入外部待办：新增 %1，更新 %2，未变 %3。": "External tasks imported: %1 added, %2 updated, %3 unchanged.",
    "来源标记已取消：%1 项。": "Marked canceled in source: %1.",
    "  ·  从 iCalendar 导入的任务 · %1": "  ·  Imported from iCalendar · %1",
    "  ·  来自 CalDAV · %1": "  ·  From CalDAV · %1",
    "  ·  来源已取消，不能完成或计时": "  ·  Canceled at source; completion and tracking are disabled",
    "  ·  来源已删除，本机记录仍保留": "  ·  Removed at source; kept on this device",
    "外部日历 · %1": "External calendar · %1",
    "外部日历事件": "External calendar event",
    "导入 iCalendar 文件": "Import iCalendar file",
    "iCalendar 文件 (*.ics)": "iCalendar files (*.ics)",
    "导出日程到 ICS": "Export planner tasks to ICS",
    "ICS 日程已导出。": "Planner tasks exported to ICS.",
    "开始任务专注": "Start a focus session",
    "启动提示": "Getting started",
    "我有点拖延，给我一个启动提示": "I feel stuck. Give me a way to get started.",
    "需要一个启动提示？": "Need a small nudge to get started?",
    "把任务缩小成一个两分钟内能完成的动作。": (
        "Shrink the task to one action you can finish in two minutes."
    ),
    "先准备好要用的文件或工具，只做开始前的一步。": (
        "Gather the files or tools you need. Just do the first setup step."
    ),
    "给自己两分钟试做时间，之后再决定是否继续。": (
        "Try it for two minutes, then decide whether to continue."
    ),
    "先移开一个干扰；如果已经很累，安排一次真正的休息。": (
        "Remove one distraction. If you are already tired, take a proper break."
    ),
    "先迈出一小步": "Take one small step",
    "不用一次完成整件事。选一个够小的下一步，然后再决定接下来怎么做。": (
        "You do not need to finish everything at once. Choose a small next step, then decide what comes after."
    ),
    "换一个方法": "Try another approach",
    "回到任务": "Back to the task",
    "新建自定义看板": "New custom board",
    "编辑当前看板": "Edit current board",
    "编辑自定义看板": "Edit custom board",
    "看板名称": "Board name",
    "例如：发布流程": "For example: release workflow",
    "按任务状态和可选标签组成列。把待办拖到其他列即可更新状态并添加列标签。": (
        "Build columns from task status and an optional tag. Drag a task to another column to update its status and add that column's tag."
    ),
    "列名称": "Column name",
    "列规则": "Column rules",
    "不限标签": "Any tag",
    "删除此列": "Remove this column",
    "添加一列": "Add a column",
    "新列 %1": "Column %1",
    "拖到列尾可排至末尾；拖到卡片上方或下方可插入排序": (
        "Drop at the end of a column to append; drop above or below a card to set its position."
    ),
    "保存看板": "Save board",
    "删除看板": "Delete board",
    "删除这个看板？": "Delete this board?",
    "只会删除看板配置，不会删除任何待办。": (
        "Only the board setup will be deleted. No tasks will be deleted."
    ),
    "包含标签：%1": "Tag: %1",
    "待办已移入此列。": "Task moved to this column.",
    "待办已移入此列并排至末尾。": "Task moved to this column and placed at the end.",
    "标准看板排序暂不可用。": "Standard board sorting is unavailable right now.",
    "看板顺序已更新。": "Board order updated.",
    "拖动任务可更改状态和列内顺序": "Drag a task to change its status or order within a column.",
    "拖到列尾可排至末尾；拖到卡片上方或下方可插入排序": (
        "Drop at the end of a column to move a task to the end; drop above or below a card to insert it in the order."
    ),
    "拖动卡片到此列，可移入并排至末尾": (
        "Drop a card here to move it into this column and place it at the end."
    ),
    "自定义看板服务暂不可用。": "Custom boards are unavailable right now.",
    "自定义看板已保存。": "Custom board saved.",
    "自定义看板已删除。": "Custom board deleted.",
    "番茄钟 · 25 分钟": "Pomodoro · 25 min",
    "Flowtime · 自由计时": "Flowtime · open-ended",
    "倒计时 · 自定义时长": "Countdown · custom duration",
    "时长（分钟）": "Duration (minutes)",
    "计时会保存到该任务；退出工作台时会自动暂停。番茄钟结束后会提醒你休息 5 分钟。": (
        "Time is saved to this task and pauses when you close the workspace. The Pomodoro timer reminds you to take a 5-minute break."
    ),
    "任务：%1": "Task: %1",
    "所属项目（留空表示不归入项目）": "Project (leave blank to remove)",
    "标签以逗号分隔；最多 12 个": "Tags separated by commas; up to 12",
    "用逗号分隔；最多 12 个": "Separate with commas; up to 12",
    "视图": "View",
    "清单": "List",
    "看板": "Kanban",
    "四象限": "Eisenhower matrix",
    "四象限规则：高优先级视为重要；日期为今天或已逾期的未完成事项视为紧急。": (
        "Eisenhower matrix rules: High-priority tasks are important; unfinished tasks due today or overdue are urgent."
    ),
    "重要且紧急": "Important and urgent",
    "重要不紧急": "Important, not urgent",
    "紧急不重要": "Urgent, not important",
    "其他事项": "Other items",
    "接下来七天": "Next seven days",
    "先看负荷，再决定节奏": "Review the workload, then set your pace",
    "上周": "Previous week",
    "下周": "Next week",
    "%1，%2": "%1, %2",
    "%1 项待安排": "%1 unscheduled",
    "留白": "Open",
    "%1 项待排": "%1 to schedule",
    "日内计划": "Daily schedule",
    "%1 · 拖动待办到合适时段": "%1 · Drag tasks to a suitable time",
    "%1 已安排 · %2 计划余量": "%1 planned · %2 available",
    "有 %1 项时间冲突": "Time conflicts: %1",
    "CalDAV 冲突处理暂不可用。": "CalDAV conflict resolution is unavailable.",
    "已采用服务器上的完成状态。": "The server's completion status was applied.",
    "已保留本机完成状态；下次同步时推送到服务器。": (
        "The local completion status was kept and will be sent to the server during the next sync."
    ),
    "本机与服务器的完成状态不同，请选择保留哪一侧。": (
        "The local and server completion states differ. Choose which one to keep."
    ),
    "采用服务器": "Use server",
    "保留本机": "Keep local",
    "待安排": "Unscheduled",
    "%1 项": "%1 items",
    "待办都已放进计划，给日程留点空白也很好。": (
        "All tasks are scheduled. It is fine to leave some room in your day."
    ),
    "未命名待办": "Untitled task",
    "减少预计用时": "Decrease estimated duration",
    "增加预计用时": "Increase estimated duration",
    "生活": "Life",
    "工作": "Work",
    "家庭": "Family",
    "个人": "Personal",
    "结束计时": "Stop timer",
    "开始计时": "Start timer",
    "排入 %1": "Schedule for %1",
    "没有完整空档": "No suitable time slot",
    "开始计时后记录实际用时": "Actual time is tracked while the timer runs",
    "%1:00 – %2:00": "%1:00 – %2:00",
    "今天还没有安排": "Nothing planned for today yet",
    "添加一项待办后，就可以把它拖到日内计划安排时间。": "Add a task, then drag it into the daily plan to choose a time.",
    "添加第一项待办": "Add your first task",
    "%1 · 实际 %2": "%1 · Actual %2",
    "缩短计划时长": "Shorten scheduled duration",
    "延长计划时长": "Extend scheduled duration",
    "结束": "Stop",
    "计时": "Track time",
    "移回待安排清单": "Move back to unscheduled tasks",
    "时间轴以外还有 %1 项，仍可在下方清单管理。": (
        "%1 more tasks are outside the timeline and can still be managed in the list below."
    ),
    "我的提醒事项": "My tasks",
    "全部": "All",
    "计划内": "Scheduled",
    "已完成": "Completed",
    "这个智能清单里暂时没有事项。": "There are no tasks in this smart list yet.",
    "%1    %2 件待完成": "%1    %2 incomplete tasks",
    "  ·  估计 %1": "  ·  Est. %1",
    "  ·  实际 %1": "  ·  Actual %1",
    "  ·  重复": "  ·  Repeats",
    "  ·  到时提醒": "  ·  Reminder due",
    "全天": "All day",
    "删除": "Delete",
    "上个月": "Previous month",
    "%1 年 %2 月": "%1/%2",
    "下个月": "Next month",
    "删除这件待办？": "Delete this task?",
    "确定删除“%1”吗？删除后无法撤回。": "Delete “%1”? This action cannot be undone.",
    "取消": "Cancel",
    "日": "S",
    "一": "M",
    "二": "T",
    "三": "W",
    "四": "T",
    "五": "F",
    "六": "S",
    # These topic labels are model-provided UI labels; only their display is
    # translated. The stable topic keys remain unchanged.
    "新闻与时事": "News & current affairs",
    "国内": "Domestic",
    "国际": "International",
    "财经商业": "Finance & business",
    "科技数码": "Technology & digital",
    "人工智能": "Artificial intelligence",
    "游戏": "Games",
    "文化影视": "Culture & film",
    "健康": "Health",
    "生活方式": "Lifestyle",
    "其他": "Other",
    # Exact Python-generated status and validation text shown through the
    # planner notice. Messages containing appended exception details will
    # fall back to their original text.
    "已切换日计划。": "Day plan updated.",
    "日程控制器尚未连接。": "The planner service is not connected.",
    "已结束计时。": "Time tracking stopped.",
    "已开始记录实际用时。": "Time tracking started.",
    "番茄钟完成，实际用时已保存。建议休息 5 分钟。": "Pomodoro complete. Time saved; take a 5-minute break.",
    "倒计时结束，实际用时已保存。": "Countdown complete. Time saved.",
    "已调整预计用时。": "Estimated duration updated.",
    "操作未完成，请检查后重试。": "The action could not be completed. Check the details and try again.",
    "已保存。": "Saved.",
    "保存异常": "Save issue",
    "草稿已保存": "Draft saved",
    "请填写待办内容。": "Enter a task.",
    "日期请使用 YYYY-MM-DD 格式。": "Enter the date in YYYY-MM-DD format.",
    "已加入日程。": "Task added to the planner.",
    "已恢复为待办。": "Marked as to do.",
    "已完成。": "Completed.",
    "日程已删除。": "Task deleted.",
    "已切换清单。": "Task list changed.",
    "已移回待安排清单。": "Moved back to unscheduled tasks.",
    "日程数据暂时无法载入。": "Planner data could not be loaded right now.",
    "日程功能暂不可用。": "The planner is not available right now.",
    "日程操作没有保存，请检查后重试。": "The planner action was not saved. Check the details and try again.",
    "日程草稿保存失败。": "The planner draft could not be saved.",
    "日程提醒暂时无法检查。": "Planner reminders could not be checked right now.",
    "关闭日程前保存实际用时失败。": "Actual time could not be saved before closing the planner.",
    "已导入数据，但日程列表无法载入。": "Data was imported, but the planner list could not be loaded.",
    "已导入数据，但日程列表无法更新。": "Data was imported, but the planner list could not be updated.",
    "日程状态无法编码为有效 JSON。": "The planner state could not be encoded as valid JSON.",
    "旧版主状态原文必须是 JSON 字符串。": "The original legacy main-state value must be a JSON string.",
    "旧版主状态必须是对象。": "The legacy main state must be an object.",
    "旧版 records 必须是对象数组。": "Legacy records must be an array of objects.",
    "旧版 settings 必须是对象。": "Legacy settings must be an object.",
    "旧版 drafts 必须是对象。": "Legacy drafts must be an object.",
    "旧版日程记录缺少有效 id，无法安全关联操作。": "A legacy planner record has no valid ID, so actions cannot be linked safely.",
    "旧版日程记录 id 重复，无法安全保存操作覆盖。": "A legacy planner record has a duplicate ID, so action overrides cannot be saved safely.",
    "旧版日程记录 data 必须是对象。": "The data for a legacy planner record must be an object.",
    "旧版日程草稿必须是对象。": "A legacy planner draft must be an object.",
    "本机日程状态结构无效。": "The local planner state has an invalid structure.",
    "本机旧日程必须是对象数组。": "Local legacy planner entries must be an array of objects.",
    "本机新增日程必须是对象数组。": "Local planner additions must be an array of objects.",
    "本机日程覆盖结构无效。": "The local planner override structure is invalid.",
    "本机日程设置或删除标记结构无效。": "The local planner settings or deletion markers have an invalid structure.",
    "本机日程草稿结构无效。": "The local planner draft has an invalid structure.",
    "本机日程草稿来源标记无效。": "The local planner draft source marker is invalid.",
    "当前计时状态无效。": "The current time-tracking state is invalid.",
    "当前计时缺少任务或开始时间。": "The current timer is missing a task or start time.",
    "当前计时的开始或检查点时间无效。": "The current timer's start or checkpoint time is invalid.",
    "当前计时的累计秒数无效。": "The accumulated seconds for the current timer are invalid.",
    "本机日程记录类型无效。": "A local planner record has an invalid type.",
    "本机日程记录 id 缺失或重复。": "A local planner record is missing an ID or has a duplicate ID.",
    "本机日程记录 data 必须是对象。": "The data for a local planner record must be an object.",
    "本机日程删除标记结构无效。": "The local planner deletion marker has an invalid structure.",
    "本机日程删除标记缺少有效类型或 id。": "The local planner deletion marker is missing a valid type or ID.",
    "无法初始化本机日程状态。": "The local planner state could not be initialized.",
    "日程时钟必须返回 datetime。": "The planner clock must return a datetime value.",
    "日程筛选条件无效。": "The planner filter is invalid.",
    "日程草稿必须是对象。": "A planner draft must be an object.",
    "待办标题不能为空。": "The task title cannot be empty.",
    "待办标题最多 60 个字符。": "The task title can contain up to 60 characters.",
    "时间必须是有效的 HH:MM 格式，或留空。": "Enter a valid time in HH:MM format, or leave it blank.",
    "优先级无效。": "The priority is invalid.",
    "清单无效。": "The task list is invalid.",
    "备注必须是文本。": "The note must be text.",
    "备注最多 100 个字符。": "The note can contain up to 100 characters.",
    "提醒开关必须是布尔值。": "The reminder setting must be a Boolean value.",
    "预计用时须为 5 至 480 分钟之间的 5 分钟倍数。": "Estimated duration must be a 5-minute increment from 5 to 480 minutes.",
    "重复周期无效。": "The repeat interval is invalid.",
    "排程开始时间须为有效的 HH:MM 格式。": "The scheduled start time must use a valid HH:MM format.",
    "任务时长须为 5 至 480 分钟之间的 5 分钟倍数。": "Task duration must be a 5-minute increment from 5 to 480 minutes.",
    "已完成的事项不能加入时间安排。": "Completed tasks cannot be added to the schedule.",
    "计时任务无效。": "The timed task is invalid.",
    "专注计时模式无效。": "The focus timer mode is invalid.",
    "倒计时须为 5 至 480 分钟。": "Countdown duration must be from 5 to 480 minutes.",
    "报表开始日期不能晚于结束日期。": "The report start date must not be after the end date.",
    "一次最多查看连续 366 天的工时。": "A timesheet can cover at most 366 consecutive days.",
    "报表开始日期 必须是 YYYY-MM-DD 格式。": "The report start date must use YYYY-MM-DD format.",
    "报表结束日期 必须是 YYYY-MM-DD 格式。": "The report end date must use YYYY-MM-DD format.",
    "请选择本机 CSV 保存位置。": "Choose a local location for the CSV file.",
    "工时导出文件须使用 .csv 扩展名。": "Timesheet exports must use the .csv extension.",
    "CSV 保存文件夹不存在。": "The CSV destination folder does not exist.",
    "工时 CSV 导出失败。": "The timesheet CSV could not be exported.",
    "请选择本机 ICS 文件。": "Choose a local ICS file.",
    "ICS 文件须使用 UTF-8 编码。": "ICS files must use UTF-8 encoding.",
    "ICS 日历无法导入。": "The ICS calendar could not be imported.",
    "请选择本机 ICS 保存位置。": "Choose a local destination for the ICS file.",
    "ICS 日程导出失败。": "Planner tasks could not be exported to ICS.",
    "ICS 文件为空。": "The ICS file is empty.",
    "ICS 文件不能超过 2 MB。": "The ICS file cannot exceed 2 MB.",
    "文件不是完整的 iCalendar（VCALENDAR）文件。": "The file is not a complete iCalendar (VCALENDAR) document.",
    "ICS 文件含有格式错误的属性行。": "The ICS file contains a malformed property line.",
    "ICS 文件包含嵌套的 VEVENT。": "The ICS file contains a nested VEVENT.",
    "ICS 文件包含没有开始标记的 VEVENT。": "The ICS file contains a VEVENT without a begin marker.",
    "ICS 中包含重复事件系列；当前导入只接受单次事件。": "Recurring ICS events are not supported by this importer yet.",
    "ICS 的 VEVENT 缺少 UID，无法安全去重。": "An ICS VEVENT has no UID, so it cannot be safely deduplicated.",
    "ICS 文件中有重复 UID，导入已取消以避免误覆盖。": "The ICS file contains duplicate UIDs; import was cancelled to avoid overwriting events.",
    "ICS 全天事件日期须使用 YYYYMMDD。": "All-day ICS events must use YYYYMMDD dates.",
    "ICS 文件含有无效的全天事件日期。": "The ICS file contains an invalid all-day event date.",
    "ICS 事件时间须使用 YYYYMMDDTHHMMSS 或 UTC 的 Z 格式。": "ICS event times must use YYYYMMDDTHHMMSS or the UTC Z format.",
    "ICS 文件含有无效的事件时间。": "The ICS file contains an invalid event time.",
    "ICS 的 UTC 时间不能同时声明 TZID。": "A UTC ICS time cannot also specify a TZID.",
    "ICS 使用了暂不支持的 DURATION 格式。": "The ICS file uses a DURATION format that is not supported yet.",
    "全天事件的 DURATION 须为正整天数。": "An all-day event duration must be a positive whole number of days.",
    "ICS 文件没有可导入的单次事件。": "The ICS file contains no importable one-time events.",
    "ICS 文件有未结束的 VEVENT。": "The ICS file contains an unterminated VEVENT.",
    "一次最多导入 500 个日历事件。": "You can import up to 500 calendar events at a time.",
    "ICS 事件的 DTSTART 数据类型不一致。": "The ICS event has an inconsistent DTSTART value type.",
    "ICS 全天事件的结束日期必须晚于开始日期。": "An all-day ICS event must end after it starts.",
    "ICS 事件的起止时区不一致。": "The ICS event has different time zones for its start and end.",
    "ICS 事件的结束时间早于开始时间。": "The ICS event ends before it starts.",
    "本机外部日历事件结构无效。": "The local external calendar data is invalid.",
    "本机日历事件 UID 缺失或重复。": "A local calendar event has a missing or duplicate UID.",
    "本机日历事件标题无效。": "A local calendar event title is invalid.",
    "本机日历全天标记无效。": "A local calendar event has an invalid all-day flag.",
    "本机日历事件日期无效。": "A local calendar event date is invalid.",
    "本机日历事件日期范围无效。": "A local calendar event date range is invalid.",
    "本机日历事件时间无效。": "A local calendar event time is invalid.",
    "本机日历事件结束时间早于开始时间。": "A local calendar event ends before it starts.",
    "本机日历事件说明、地点或来源无效。": "A local calendar event has invalid details, location, or source.",
    "本机日历事件字段超出长度限制。": "A local calendar event field exceeds the allowed length.",
    "ICS 导出日期无效。": "The ICS export date is invalid.",
    "ICS 导出开始日期不能晚于结束日期。": "The ICS export start date must not be after its end date.",
    "iCalendar 文件须使用 .ics 扩展名。": "iCalendar files must use the .ics extension.",
    "iCalendar 保存文件夹不存在。": "The iCalendar destination folder does not exist.",
    "已完成的事项不能开始计时。": "Time tracking cannot start for a completed task.",
    "请先结束当前任务的计时，再开始另一项。": "Stop the current timer before starting another task.",
    "当前计时的检查点时间无效。": "The current timer's checkpoint time is invalid.",
    "日程 id 无效。": "The planner ID is invalid.",
    "请先结束这项任务的计时，再删除它。": "Stop this task's timer before deleting it.",
    "这项待办已不存在，列表已刷新。": "This task no longer exists. The list has been refreshed.",
    "这项日程已不存在，列表已刷新。": "This planner entry no longer exists. The list has been refreshed.",
    "已切换到 %1，请在“待安排”里确认时间。": "Switched to %1. Confirm the time in Unscheduled.",
    "今天暂时找不到完整空档，请从“待安排”里拖动或选择时间。": "No open slot is long enough today. Drag this item from Unscheduled or choose a time.",
    "已保存到待安排：%1": "Saved to Unscheduled: %1",
    "现在安排": "Schedule now",
    "查看这天": "View this day",
    "稍后安排": "Schedule later",
}
