"""English translations for the shopping-list Qt Quick page."""

ENGLISH_CATALOG: dict[str, str] = {
    "商品分类": "Item category",
    "购买优先级": "Purchase priority",
    "物品名称": "Item name",
    "数量": "Quantity",
    "预计单价": "Estimated unit price",
    "备注": "Note",
    "已保存。": "Saved.",
    "操作未完成，请检查后重试。": "The operation didn't complete. Check the details and try again.",
    "请填写物品名称。": "Enter an item name.",
    "物品已加入待买清单。": "Item added to the shopping list.",
    "已切换清单视图。": "Shopping list view changed.",
    "已移回待买清单。": "Moved back to the shopping list.",
    "已标记为买到。": "Marked as purchased.",
    "这件物品": "this item",
    "物品已删除。": "Item deleted.",
    "删除这件物品？": "Delete this item?",
    "删除后，这件物品不会再出现在当前本机待买清单；导入的旧版原始数据不会被改动。": (
        "After deletion, this item will no longer appear in the current local shopping list; imported legacy source data stays unchanged."
    ),
    "取消": "Cancel",
    "删除": "Delete",
    "待买清单": "Shopping list",
    "本机保存 · 导入的旧版数据不会被改动": "Saved locally · Imported legacy data will not be changed",
    "待买物品": "Shopping items",
    "食品": "Food",
    "日用品": "Household supplies",
    "家居": "Home",
    "数码": "Electronics",
    "药品": "Medicine",
    "其他": "Other",
    "预计金额": "Estimated total",
    "本月买到": "Purchased this month",
    "加入满七天": "On list for 7+ days",
    "%1 件": "%1 items",
    "待买观察": "Shopping list insights",
    "当前没有待买条目。": "There are no items on your list right now.",
    "最早加入 · %1 · %2 · %3 天": "Oldest item · %1 · %2 · %3 days",
    "%1 · %2 · %3": "%1 · %2 · %3",
    "预计 %1": "Est. %1",
    "价格待定": "Price TBD",
    "已加入七天以上": "Added more than 7 days ago",
    "加入未满七天": "Added less than 7 days ago",
    "想买先记下": "Add an item to your list",
    "物品名称，例如：洗衣液、燕麦奶": "Item name, e.g. laundry detergent or oat milk",
    "必填：物品名称，例如：洗衣液、燕麦奶": "Required: item name, e.g. laundry detergent or oat milk",
    "必填，例如：洗衣液、燕麦奶": "Required, e.g. laundry detergent or oat milk",
    "数量，例如：2 盒": "Quantity, e.g. 2 boxes",
    "例如：2 盒": "E.g. 2 boxes",
    "预计单价（元，可留空）": "Estimated unit price (CNY, optional)",
    "元，可留空": "CNY, optional",
    "有空买": "Whenever convenient",
    "急需": "Urgent",
    "等等再买": "Buy later",
    "备注：品牌、规格或购买渠道": "Note: brand, size, or where to buy",
    "品牌、规格或购买渠道": "Brand, size, or where to buy",
    "加入待买清单": "Add to shopping list",
    "清单": "List",
    "待买": "To buy",
    "全部": "All",
    "已买": "Purchased",
    "移回待买清单": "Move back to shopping list",
    "标记为已买": "Mark as purchased",
    "数量未填": "Quantity not set",
    "待定": "TBD",
    "预计": "Planned",
    "待买清单已经清空": "Your shopping list is empty.",
    "这里还没有物品": "There are no items here yet.",
}

DISAMBIGUATED_ENGLISH_CATALOG: dict[tuple[str, str], str] = {
    ("待买物品", "shopping item count"): "Shopping items",
    ("待买物品", "shopping item fallback"): "Shopping item",
    ("待买", "shopping status"): "To buy",
}
